### ISSUE TITLE
clean: true problem

### ISSUE THREAD

**Issue by scaryguy** [roo-rb/roo#101]
Hi,

In order to get rid off whitespace problem with headers I tried to use `clean: true` option. It worked. Well, particularly...

There is an implementation problem with  `clean` option because it removes ALL unicode characters in the sheet... But all I wanted it to remove white spaces at the headers.

I don't think that this gem is only for english language? :)

Would be cool if there's an option for ONLY cleaning up headers.

Thank you

**Comment by stevendaniels** [comment]
Can anyone comment on why the :clean option removes all non-ASCII characters?

**Comment by stevendaniels** [comment]
@simonoff @Empact Should we reconsider what the :clean option does?

**Comment by mwmalinowski** [comment]
@stevendaniels 
*If* the `:clean` option is intended to mirror the Excel function CLEAN() then its main purpose is to remove control codes[1].  That is *not* what the `clean_sheet` method does--it removes UTF characters with codes >=127 and then any leading and trailing ASCII whitespace[2] via Ruby's String#strip. 

This means that non-printable non-whitespace ASCII characters (e.g. SOH) *will not* be removed... which... seems like strange behavior to me. 

Also, as @scaryguy pointed out, the `:clean` option paints with a brush that's probably too broad. I don't think one would normally expect the word "clean" in this context to mean removing ™ ü é or a boatload of other legitimate, printable UTF characters.


[1] https://support.office.com/en-us/article/CLEAN-function-334d8a17-c9e1-4d8e-96c2-c89530201f4d
> Removes all nonprintable characters from text. Use CLEAN on text imported from other applications that contains characters that may not print with your operating system. For example, you can use CLEAN to remove some low-level computer code that is frequently at the beginning and end of data files and cannot be printed.
>
>IMPORTANT   The CLEAN function was designed to remove the first 32 nonprinting characters in the 7-bit ASCII code (values 0 through 31) from text. In the Unicode character set, there are additional nonprinting characters (values 127, 129, 141, 143, 144, and 157). By itself, the CLEAN function does not remove these additional nonprinting characters.



[2] I'm emphasizing that String#strip only removes ASCII whitespace characters. Non-breaking spaces, for instance, are not removed by String#strip:
```` ruby
# a0 = non-breaking space
# 20 = regular ASCII space
irb(main):001:0> "\u{a0}hello\u{20}".strip
=> " hello"

**Comment by stevendaniels** [comment]
In my opinion, the :clean option should match the office description.

I also think it should remove Unicode spaces in addition to ASCII spaces. When would keeping Unicode spaces be a desired result?
Something like this would work. I'll turn it into a pull request.

    def sanitize_value(v)
      v.gsub(/[[:cntrl:]]|^[\p{Space}]+|[\p{Space}]+$/, '')
    end
