### ISSUE TITLE
Roo shouldn't depend on Zip

### ISSUE THREAD

**Issue by marcofognog** [roo-rb/roo#128]
If I don't have the zip gem installed I get an error:

lib/roo/generic_spreadsheet.rb:5:in `require': cannot load such file -- zip/zipfilesystem (LoadError)
	from /home/marco/.rvm/gems/ruby-2.1.0/gems/roo-1.11.2/lib/roo/generic_spreadsheet.rb:5:in `<top (required)>'
	from /home/marco/.rvm/gems/ruby-2.1.0/gems/roo-1.11.2/lib/roo/excel.rb:13:in `<top (required)>

Since it uses RubyZip, it shouldn't depend on Zip. Also, Zip and RubyZip both use the Zip namespace, which causes problems and confusion.

**Comment by stevendaniels** [comment]
Recommend closing this issue.

**Comment by stevendaniels** [comment]
@simonoff Since this doesn't effect the master branch, I recommend closing this issue.
