### ISSUE TITLE
is not an Excel file for .xsl file

### ISSUE THREAD

**Issue by edipofederle** [roo-rb/roo#132]
I receive this error when try read a .xsl file. I am using this code:

    Roo::Excel.new(file.path)

The input file can be found here https://dl.dropboxusercontent.com/u/6730822/clients_roo_test.xls

Thanks

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.

**Comment by stevendaniels** [comment]
I'm closing this issue. Opening .xsl or .xslt files should probably be handled by ```roo-xls```.
