### ISSUE TITLE
All integers are treated as Float data type by default in .xls

### ISSUE THREAD

**Issue by yrmallu** [roo-rb/roo#133]
For phone numbers and other fields it's showing Float datatype

undefined method `split' for 99999999.0:Float

**Comment by stevendaniels** [comment]
While this issue is related to ```xls``` support, which has been moved to the ```roo-xls``` gem, the behavior still exists in the master branch of Roo. 

Fixing the way types are managed would be a big change.

**Comment by stevendaniels** [comment]
#240 resolves this issue.   Add the following to your gemfile to install it.

    gem 'roo', git: 'git://github.com/roo-rb/roo.git' 

I will work on publishing a new version of the gem to Rubygems this weekend.
