### ISSUE TITLE
IOError: The handle is invalid

### ISSUE THREAD

**Issue by naveedkakal** [roo-rb/roo#137]
IOError: The handle is invalid
        from org/jruby/RubyIO.java:1850:in `rewind'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/ruby-ole-1.2.11.7/lib/ole/storage/base.rb:110:in `load'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/ruby-ole-1.2.11.7/lib/ole/storage/base.rb:79:in `initialize'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/ruby-ole-1.2.11.7/lib/ole/storage/base.rb:85:in `open'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/spreadsheet-0.9.7/lib/spreadsheet/excel/reader.rb:1276:in `setup'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/spreadsheet-0.9.7/lib/spreadsheet/excel/reader.rb:134:in `read'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/spreadsheet-0.9.7/lib/spreadsheet/excel/workbook.rb:32:in `open'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/spreadsheet-0.9.7/lib/spreadsheet.rb:63:in `open'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/spreadsheet-0.9.7/lib/spreadsheet.rb:69:in `open'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/roo-1.13.2/lib/roo/excel.rb:40:in `initialize'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/roo-1.13.2/lib/roo/base.rb:565:in `make_tmpdir'
        from C:/jruby-1.7.8/lib/ruby/shared/tmpdir.rb:96:in `mktmpdir'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/roo-1.13.2/lib/roo/base.rb:564:in `make_tmpdir'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/roo-1.13.2/lib/roo/excel.rb:31:in `initialize'
        from (irb):8:in `evaluate'
        from org/jruby/RubyKernel.java:1123:in `eval'
        from org/jruby/RubyKernel.java:1519:in `loop'
        from org/jruby/RubyKernel.java:1284:in `catch'
        from org/jruby/RubyKernel.java:1284:in `catch'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
        from C:/jruby-1.7.8/lib/ruby/gems/shared/gems/railties-3.2.17/lib/rails/commands.rb:41:in `(root)'
        from org/jruby/RubyKernel.java:1084:in `require'
        from script/rails:6:in `(root)'irb(main):009:0>

Environment Details:

JRuby 1.7.8 (1.9.2 mode)
Rails 3.2.17
OS: Windows 8

I've been having a hard time getting Roo to run again since updating to ruby 1.9.2, any ideas on how to get past this error?

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Does any one know if this issue still exists in the current version of Roo?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.

**Comment by stevendaniels** [comment]
I'm closing this issue. If you're still having this issue, then create a gist to replicate it and I will reopen.

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.
