### ISSUE TITLE
Accessing Multiple Sheets in Excel

### ISSUE THREAD

**Issue by sheenz** [roo-rb/roo#140]
I am trying to get data from excel files onto our database, and repeatedly running into this issue where my program refuses to access other sheets in the excel document. 

For example: 
works_sheet = xlsx.sheet(0)
chapter_sheet = xlsx.sheet(1)

When using works_sheet, things are fine. But when trying to use chapter_sheet later in the code, it takes the data off of sheet 0 and doesn't access anything on the sheet it's supposed to (1). 

Any tips?

**Comment by stevendaniels** [comment]
Does anyone know if this is still an issue in the current version of Roo?
Was this issue fixed with that pull request?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.
