### ISSUE TITLE
Can I close a spreadsheet?

### ISSUE THREAD

**Issue by TechRsch** [roo-rb/roo#143]
After processing, I'd like to close the spreadsheet so that I can rename/move/delete it.  Is that possible?

**Comment by chase439** [comment]
I'm having the same issue. I can't delete the file after doing:

    file = Rails.root.join("folder1", "file1.xls").to_s
    s = Roo::Excel.new(file)
    File.delete(file)  # => Errno::EACCES: Permission denied

**Comment by stevendaniels** [comment]
@chase439 , which version of Roo are you using?

**Comment by chase439** [comment]
I'm using version 1.13.2

**Comment by stevendaniels** [comment]
This issue affects an older version of Roo.

You'll need to add the following to your gemfile to install the most current version.
    gem 'roo', git: 'git://github.com/roo-rb/roo.git'

Please let me know if the issue still exists in the current version of Roo.

**Comment by chase439** [comment]
The latest code works and allows for file deletion. Could you please make another version of Roo with the latest code on rubygems?

**Comment by stevendaniels** [comment]
I created an issue for [updating Roo on RubyGems](https://github.com/roo-rb/roo/issues/172)

Can we close this issue?

**Comment by chase439** [comment]
I'm fine with you closing this issue. Thanks for the help!

**Comment by medexdev** [comment]
I'm still unable to delete it. Here's what I did.
require 'roo-xls'
s = Roo::Excel.new('abc.xls')
s.to_csv('abc.csv')
File.delete('abc.xls')
I got permission error. I tested on both windows and linux. I also tried using just spreadsheet.
s = Roo::Spreadsheet.open('abc.xls')
The rest is the same as above. I still got permission error. please advise. Thanks.

**Comment by stevendaniels** [comment]
@medexdev It looks like you're using version 1.13.2.
That issue is fixed in 2.0.0.

Roo version > 2 isn't available on RubyGems. It's only available on github. Add the following to your gemfile to install it.

    gem 'roo', git: 'git://github.com/roo-rb/roo.git'

**Comment by stevendaniels** [comment]
This issue is fixed in roo 2.0.0, which is available on Rubygems.

**Comment by TechRsch** [comment]
Okay, can you tell me how to close a spreadsheet?  Nothing I've tried does that.  Thanks.

**Comment by stevendaniels** [comment]
@TechRsch did you notice this problem with xlsx files or with xls files? 

Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

Thanks.

**Comment by TechRsch** [comment]
@stevendaniels  Okay, I get it.  I couldn't figure out how to get it closed and rename kept throwing an error.  However, it doesn't need to be closed?  And, rename was throwing the error not because it was open but because I had the rename wrong which I missed because I thought it was open.  Thanks.

**Comment by TechRsch** [comment]
In #221, you mentioned that you would reopen #143 and look into my question. Is what I need possible?  Thank you.

**Comment by stevendaniels** [comment]
@TechRsch Could you give more details about what you're trying to do? It would be really helpful if you provided a code sample that illustrates what is going wrong.

**Comment by stevendaniels** [comment]
I'm closing this issue. Without anymore information, I can't properly determine if this issue still exists. If anyone encounters this issue, please submit a gist with the offending code.

**Comment by aminzer** [comment]
I've already opened issue in https://github.com/roo-rb/roo-xls/issues/40 but thought that problem might be related not to roo-xls, but roo.

@stevendaniels, Can you please answer on question in https://github.com/roo-rb/roo-xls/issues/40  ?
