### ISSUE TITLE
RuntimeError: Unknown Codepage 0x906c 

### ISSUE THREAD

**Issue by henb** [roo-rb/roo#144]
See http://stackoverflow.com/questions/25231208/how-to-fix-the-error-in-spreadsheet-gem-unknown-codepage-0x906c

Please help fix this error!

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.

**Comment by stevendaniels** [comment]
This issue was caused by spreadsheet gem, not roo. Closing this issue.
