### ISSUE TITLE
Formatting of numbers

### ISSUE THREAD

**Issue by rishijain** [roo-rb/roo#146]
I am parsing an xls/xlsx file. Each row has values like 1.23, 1.0916, ... etc, basically float numbers. When I read it, it changes few values. For ex: 

File has 1.0916, it changes to 1.091600000000001
File has 1.0877, it changes to 1.0877000000000001

But it does not happen with every value thats in there, it happens with only few.

Any clue why it is behaving this way?

**Comment by stevendaniels** [comment]
Since this isn't an issue with Roo, I think this issue should be closed.

**Comment by rishijain** [comment]
Yes, this is not an issue with roo.
