### ISSUE TITLE
Header regexps should be regexps

### ISSUE THREAD

**Issue by airblade** [roo-rb/roo#156]
I just ran into a problem where I was looking for the header `Body (HTML)`.  I specified `description: 'Body (HTML)'` in the hash I passed to `xls.parse`.  The `parse` method wasn't able to find my header because it treated the text I gave as a regexp instead of a string.

The README says you can use regexp characters in the string:

```ruby
xls.parse(:id => 'UPC*SKU',:qty => 'ATS*\sATP\s*QTY$')
```

However I think this would be better handled by using a real regexp when you want a regexp and a string when you want a string.  For example:

```ruby
xls.parse(:id => /UPC*SKU/, :qty => /ATS*\sATP\s*QTY$/, :description => 'Body (HTML)')
```

**Comment by stevendaniels** [comment]
This seems like it would be a good pull request. 
@airblade : Could you turn you changes into a pull request?

**Comment by airblade** [comment]
@stevendaniels Here you go: #173.

**Comment by stevendaniels** [comment]
Merged! 
I recommend closing this issue.
