### ISSUE TITLE
Roo isn't being updated on RubyGems

### ISSUE THREAD

**Issue by stevendaniels** [roo-rb/roo#172]
The latest version of [Roo on RubyGems](https://rubygems.org/gems/roo) is 1.13.2 from December 23, 2013. There's been a lot of good work put into Roo since then. Pushing these changes to RubyGems would be good for the community.

In addition, gems like roo-xls and roo-google should also be published to RubyGems.

**Comment by stevendaniels** [comment]
After looking at all of Roo's opened issues, I noticed that a good portion of them are related to the RubyGems version of Roo (e.g. https://github.com/roo-rb/roo/issues/143).

@Empact @hmcgowan @thopre : I noticed that @simonoff is the maintainer of roo-rb/roo, but he isn't listed as an owner on RubyGems. Would it be possible to add him?

**Comment by pmneve** [comment]
I very much agree that roo is overdue for a rubygems update.   I'm stuck behind a corporate firewall that makes updating directly from github painful when I can get it to work...  And I use 1.13.2 very heavily.

**Comment by pjar** [comment]
Another call for update on RubyGems

**Comment by reshleman** [comment]
Thanks for opening this, @stevendaniels. It would be incredibly helpful to have an updated version of Roo released on RubyGems, in addition to an initial release of `roo-xls` and `roo-google`.

**Comment by kimrgrey** [comment]
Any news about upcoming release?

**Comment by andyw8** [comment]
@pmneve try configuring git to push over https instead of the git protocol. It's usually much more firewall-friendly.

**Comment by Empact** [comment]
@simonoff Happy to add you to rubygems - just need your email.

**Comment by Empact** [comment]
Is anyone else interested in helping maintain the library? It doesn't make sense for me to do so as I don't use spreadsheets in any of my current projects.

**Comment by stevendaniels** [comment]
I'd be interested in helping maintain the library. I've been trying to help triage different issues and submit patches over the past few months.

**Comment by Empact** [comment]
Great - then I can give you the ability to release to solve this issue as well. I just made you a maintainer - can you give me your email address? I'll need it to add you to rubygems. You can send it to ben.woosley@gmail.com if you prefer.

But will be great to get a release out! You might want to start with a release candidate first to get some more testing in the wild before moving everyone over.

**Comment by stevendaniels** [comment]
Thanks!

I'm going to take another look at the open issues to decide if there are any that should be solved before a release candidate. 

Going forward, is there a list of ideas anywhere (including inside your head) for features you think should be added?

**Comment by simonoff** [comment]
@Empact alex at simonov dot me

**Comment by stevendaniels** [comment]
I think we should push a 2.0.0-pre version of the gem as is and fix any issues we encounter before the 2.0.0 release.

@Empact I sent you my email address. Please let me know when you've added me to rubygems.

**Comment by pmneve** [comment]
Sounds like a good plan

**Comment by stevendaniels** [comment]
I think things are ready to move forward. Off the top of my head, here are the changes we need to address.

1. update the gemspec to 2.0.0-rc.1
2. update the documentation
3. create roo-xls and roo-google gems that use the proper roo dependency
    * spec.add_runtime_dependency 'roo', '>= 2.0.0.rc.1', '< 3'

My biggest concern is the documentation. Being a major release, there are a lot of things that have changed, with the extraction for roo-xls and roo-google being the biggest changes. There are also a few methods that changed significantly (like Roo::Excelx#formula?), we should find those methods and mention them in the updated Readme.

@simonoff Can you think of anything else that needs to be done for the release?

**Comment by stevendaniels** [comment]
I've submitted a pull request (#189) that decreases the number of Roo's public methods. It's a minor change, but it will be useful moving forward. If those methods are public in the 2.0.0 release, they will need to stay until 3.0.0.

I don't think any of those methods needed to be public.

**Comment by simonoff** [comment]
@stevendaniels I think in `beta` release we will need to doing exception about format and methods less aggressive. Instead of raise exception we will only inform user what this is deprecated or something like this. And `beta` release will need to have `roo-xls` and `roo-google` as a runtime dependency.

**Comment by stevendaniels** [comment]
Adding roo-xls and roo-google as runtime dependencies is a good idea. 

Are we tagging the release as 2.0.0-beta?

**Comment by stevendaniels** [comment]
Updated the  Readme. #190
Do we need any other changes before a beta release?

**Comment by simonoff** [comment]
Yes, I need to fix tests for roo-google.

**Comment by fro** [comment]
Any news about upcoming release?

**Comment by simonoff** [comment]
@fro I need to fix `roo-google` first. If it not so critical I can make a beta release on this week.

**Comment by fro** [comment]
@simonoff Indeed, it is not critical.
I've used the current github roo (`gem 'roo', git: 'git@github.com:roo-rb/roo.git'`) and it's working like a charm.
Thank you for maintaining this great gem.

**Comment by simonoff** [comment]
@fro are you used new version with new google library without password auth? oauth works fine?

**Comment by fro** [comment]
@simonoff I'm not using roo-google.

**Comment by simonoff** [comment]
So I released `2.0.0-beta1` release. If all will be ok, then I will release `2.0.0` on next week.

**Comment by stevendaniels** [comment]
2.0.0 was released yesterday. Great job @simonoff !
