### ISSUE TITLE
Possible to define "optional" header column names? they may or may not exist?

### ISSUE THREAD

**Issue by joshuairl** [roo-rb/roo#178]

**Comment by joshuairl** [comment]
To elaborate...

```ruby
xls.parse(:clean => true,
          :firstname => 'FIRST*',
          :middlename => 'MIDDLE*',
          :lastname => 'LAST*',
          :email => 'EMAIL',
          :certname => 'CERTNAME',
          :degree => 'DEGREE',
          :completed_date => 'DATE*',
          :address1 => 'ADDRESS1',
          :address2 => 'ADDRESS2',
          :city => 'CITY',
          :state => 'STATE',
          :country => 'COUNTRY',
          :zipcode => 'ZIPCODE',
          :phone1 => 'PHONE1',
          :phone1ext => 'PHONE1EXT',
          :phone2 => 'PHONE2',
          :phone2ext => 'PHONE2EXT',
          :fax => 'FAX',
          :faxext => 'FAXEXT',
          :hours => 'HOURS'
        )
```

If one of these doesn't exist, then it says "Could not find header row." but I would like some of them to be optional so the excel has the option to be shorter for usability purposes

**Comment by joshuairl** [comment]
Was trying to use regex and in the readme it looks like this:
```ruby
xls.parse(:id => /UPC|SKU/,:qty => /ATS*\sATP\s*QTY\z/)
```
But that seems to throw:
`undefined method `split' for /UPC|SKU/:Regexp`

**Comment by joshuairl** [comment]
Tried :header_search method like so and still get the same "split" error
```ruby
records = xls.parse(
          :header_search => [/FIRST/]
        )
```

Maybe I'm missing something :( sorry

**Comment by stevendaniels** [comment]
Which version of Roo are you using?

**Comment by joshuairl** [comment]
Was running the latest release the I decided to check bleeding edge then went back to release so who knows! Sorry for the shotty debug efforts on my part.  I did give up on regex due to errors. But can't complain because the project is amazing.

**Comment by stevendaniels** [comment]
RE Optional Headers:

I'm not sure if @simonoff wants to add a feature like this, but I feel it could be useful. We would probably need to add an ```options``` parameter to the ```row_with``` method in ```Roo::Base```. 


Re issue parsing regex. This should be made into a separate issue.

**Comment by ArthurN** [comment]
I needed optional headers, too, so I whipped up a fork. The code changes are pretty simple, but I haven't backed it up with tests (yet), so hence no PR. Maybe I could get some preliminary feedback from the community if this is worthwhile?

https://github.com/ArthurN/roo/commit/69c5e6fc561601327526393e8bd10f2727aa4c44

Usage:
```
headers = { first_name: /FIRST/i, last_name: /LAST/i, email: /EMAIL/i }
employees = xls.parse(header_line: 1, headers_to_match: headers, clean: true)
```

It allows you to specify headers which may or may not exist, and it doesn't care about header order.

I am using it in production, but nothing mission critical (just rake tasks), so YMMV.

**Comment by awh-tokyo** [comment]
I would really love this function.  I need to import data from a variety of human-generated sources that may or may not include each column of information.  This would let me import most of that with a single routine.

**Comment by simonoff** [comment]
@ArthurN make a PR.

**Comment by stevendaniels** [comment]
Closing this issue for now. I'd definitely welcome a PR for this feature.
