### ISSUE TITLE
NoMethodError: `read_cells` for `Roo::Excelx` when using `parse` with `clean: true` (XLSX)

### ISSUE THREAD

**Issue by reshleman** [roo-rb/roo#182]
Attempting to call `parse` on an `xlsx` spreadsheet with `clean: true` results in:

```
NoMethodError: undefined method `read_cells' for #<Roo::Excelx>
```

I'm encountering this on the latest revision of `master`, which `Roo::VERSION` claims to be `2.0.0`, but which is actually un-tagged and un-released on RubyGems.

I've created a gist with reproduction steps and a backtrace, in case that's helpful.
https://gist.github.com/reshleman/effae77c02e48305917c

**Comment by stevendaniels** [comment]
I did some investigating.

For some reason, ```Roo::Excelx``` doesn't have ```read_cells``` method like ```Roo::CSV``` and ```Roo::OpenOffice```. 

All ```Roo::Base``` methods that reference the ```read_cells``` except for ```clean_sheet``` are overridden. This issue could be fixed by overriding ```clean_sheet``` method to ```Roo::Excelx```.

I'm working on tests and a pull request.
