### ISSUE TITLE
NoMethodError: `each_pair` for `nil:NilClass` when using `parse` with `clean: true` (CSV)

### ISSUE THREAD

**Issue by reshleman** [roo-rb/roo#183]
Attempting to call `parse` on a `csv` spreadsheet with `clean: true` results in:

```
NoMethodError: undefined method `each_pair' for nil:NilClass
```

I'm encountering this on the latest revision of `master`.

I've created a gist with reproduction steps and a backtrace, in case that's helpful.
https://gist.github.com/reshleman/d8dd9882ca89e01d1bbe

/cc #182

**Comment by stevendaniels** [comment]
I'm looking into this issue.  Thanks for the very helpful gist! :clap:

**Comment by stevendaniels** [comment]
```csv``` does not store cells the way other formats do.  Here's the offending method. 

    # lib/roo/base.rb
    def clean_sheet(sheet)
      read_cells(sheet)
      @cell[sheet].each_pair do |coord, value|
          if value.is_a?(::String)
            @cell[sheet][coord] = sanitize_value(value)
          end
       end
      @cleaned[sheet] = true
    end


```@cell[sheet]``` should be ```@cell```

This method fixes the issue.

    # lib/roo/csv.rb
    def clean_sheet(sheet)
      read_cells(sheet)
      @cell[sheet].each_pair do |coord, value|
          if value.is_a?(::String)
            @cell[sheet][coord] = sanitize_value(value)
          end
       end
      @cleaned[sheet] = true
    end

Need to add test cases and submit a pull request.
