### ISSUE TITLE
Add support for text formatting information extraction

### ISSUE THREAD

**Issue by rayburn** [roo-rb/roo#185]
It would be great if the gem could preserve the cell text formatting during parse as an option. The current parse converts everything to straight text it seems. I need to be able to preserve the text formatting of a cell.

For example the following cell contents currently get converted to 'This text is bold and this is not' without any formatting iformation.

**This text is bold** and this is not

What would be great is if it stored the text as the following:

\<b\>This text is bold\<\b\> and this is not

Perhaps have support for bold, italic, underline, subscript, superscript and other common text formats.

Thanks for the consideration.

**Comment by stevendaniels** [comment]
I agree it would be better to have some method that preserves the cell's text formatting. I'm still getting familiar with how ```Roo``` deals with formatting.

It probably makes sense to work on adding them after updating ```Roo``` on rubygems. (#172)

**Comment by rayburn** [comment]
Thx stevendaniels.  Let me know how I can help.  In the semiconductor industry there is increasing usage of spreadsheets for content authoring and the text formatting information is key.  Current workaround is to save the file as Excel 2003 XML and find the information there and do a substitution.  Of course that is ugly...

**Comment by stevendaniels** [comment]
In case you're interested in scratching your own itch, you can get the formatting details in the sharedStrings.xml file. ``lib/roo/excelx/shared_strings.rb`` extracts those strings, but it looks like it just throws away the format information. 

Here's a link to the [sharedStrings schema](https://msdn.microsoft.com/en-us/library/office/gg278314.aspx).

**Comment by rayburn** [comment]
sounds good, i think i will start scratching.  will be good to get my first pull request out of the way!

**Comment by stevendaniels** [comment]
@rayburn Any progress on this issue?

**Comment by lukas2342** [comment]
i suppose that there hasn't been a post about it here means that this feature is not available yet?

**Comment by stevendaniels** [comment]
Closing due to lack of interest.
