### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?)

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [roo-rb/roo#201]
I am trying to use Roo to parse excel files and I get the following error:

2.1.2 :012 > Roo::Spreadsheet.open( "/Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls" )
URI::InvalidURIError: bad URI(is not URI?): /Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls
	from /Users/merlino/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split'
	from /Users/merlino/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
	from /Users/merlino/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'

Why am I getting this error?

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

Try installing the beta version of Roo:

    gem install roo -v 2.0.0beta1

**Comment by stevendaniels** [comment]
Please try the current version of Roo (2.0.0). It's available on Rubygems.
