### ISSUE TITLE
ArgumentError: Can't detect the type of /Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls - please use the :extension option to declare its type.

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [roo-rb/roo#202]
After upgrading the gem to beta version 2, I am now getting this error:

 >   Roo::Spreadsheet.open( "/Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls")
ArgumentError: Can't detect the type of /Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls - please use the :extension option to declare its type.

I have a directory full of xls and xlsx files. Some of those xls files are saved as 2003 and others 2007. So I don't know which type of xls file I will be dealing with. I need iterate through them all and open them. So why is it asking me to use the :extension option?

**Comment by stevendaniels** [comment]
Roo doesn't do mime detection. It's not a central issue for the gem. If you need to find a gem for detecting Mime Types, I suggest you search on ruby-toolbox.com or on stackoverflow.com. 

You can get around the limitation by using the solution in #203. Hope that helps.

I'm closing this issue.

**Comment by simonoff** [comment]
@TheRealGuardDogGPS I propose to you use `begin` and `rescue` to catch such situation. Trying to open file as xls if raised then it's xlsx.
