### ISSUE TITLE
Time-formatted cells not interpreted properly

### ISSUE THREAD

**Issue by Olathe** [roo-rb/roo#21]
To reproduce:

1. Create a spreadsheet on Google Docs
2. Put `4:00:02` in the first cell
3. Use `Format` menu, `Number`, `Time`
4. Use `File` menu, `Download as`, `Microsoft Excel (.xlsx)`
5. Load file into Excel and see that it's properly recognized as Time formatted
6. Load file into Roo and see that it's only a Float

**Comment by stevendaniels** [comment]
This looks like it still might be an issue. It seems like [Roo::Excelx](https://github.com/roo-rb/roo/blob/master/lib/roo/excelx.rb#L121-L122) parses Time as a float.

Can anyone confirm that this issue still exists in the current version of Roo?

**Comment by stevendaniels** [comment]
I've looked into ```roo/excelx.rb``` and it looks like the issue still exists

https://github.com/roo-rb/roo/blob/master/lib/roo/excelx.rb#L112-L128

    def type_cast_value(value)
      case @type
      ...
      when :time
        value.to_f*(24*60*60)
      ...
      end
    end


Changing this should be part of a larger project that deals with types. #133 #86 #139 #53, etc

**Comment by kakoni** [comment]
You could pass that float to time object-> ```Time.at(value).utc.strftime("%H:%M%S")``` perhaps?

**Comment by stevendaniels** [comment]
A short update. I've been working on some updates that will address this and the other type-related issues. Please continue to be patient.

**Comment by yjukaku** [comment]
:+1: Awesome, thanks @stevendaniels

**Comment by stevendaniels** [comment]
This issue should be resolved in the master branch.  Add the following to your gemfile to install it.

    gem 'roo', git: 'git://github.com/roo-rb/roo.git'
