### ISSUE TITLE
please use the :extension option to declare its type when extension is declard.

### ISSUE THREAD

**Issue by TechRsch** [roo-rb/roo#218]
I converted from Roo 1.13.2 to Roo 2.0.0.  I am trying to read an Excel file that I've read many times under the old Roo.  2.0.0 required a type declaration.  However, even when I declared its type, Roo responded with that same message.

a_file = Roo::Spreadsheet.open(gsub_f, extension: :xls)
...
ArgumentError: Can't detect the type of (filename).xls - please use the :extension option to declare its type.

**Comment by stevendaniels** [comment]
@TechRsch If you're reading a legacy Excel spreadsheet (xls), you'll need to add the `roo-xls` gem.

Are you loading roo-xls in your project?

**Comment by TechRsch** [comment]
@stevendaniels  Yes, I converted to using Excelx.new with roo-xls and it's working great.  Thanks
