### ISSUE TITLE
performance issues - how to improve loading speed

### ISSUE THREAD

**Issue by ipstone** [roo-rb/roo#22]
hello, I am loading up a reasonable size xlsx file 2M, but Roo is taking so long to load it, whereas using python xlrd, it seems instantenous, what might take it so long for Roo to load it? is this a general issue or it might be my file ?

thanks

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Does any one know if this issue still exists in the current version of Roo?

**Comment by pmneve** [comment]
Update the rubygem so those of us with privacy/security issues to fight can get the latest version.

**Comment by stevendaniels** [comment]
I recommend closing this issue.

**Comment by why-el** [comment]
This is still an issue in the latest version (`2.1.0`). A 15mb file spikes to 5+GB, basically the same as reported by @alexlod.

**Comment by stevendaniels** [comment]
The high memory usage is another issue. See #179.
