### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by xjz19901211** [roo-rb/roo#225]
Hello， I use Windows. cannot parse xlsx file
```
c:/Ruby21/lib/ruby/2.1.0/tmpdir.rb:85:in `mkdir': Invalid argument @ dir_s_mkdir
 - C:/Users/xjz/AppData/Local/Temp/roo_F:\example.xlsx20150615-2300-nbopo5 (Errn
o::EINVAL)
        from c:/Ruby21/lib/ruby/2.1.0/tmpdir.rb:85:in `block in mktmpdir'
        from c:/Ruby21/lib/ruby/2.1.0/tmpdir.rb:142:in `create'
        from c:/Ruby21/lib/ruby/2.1.0/tmpdir.rb:85:in `mktmpdir'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/roo-2.0.0/lib/roo/base.rb:519:in
 `make_tmpdir'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/roo-2.0.0/lib/roo/excelx.rb:262:
in `initialize'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/roo-2.0.0/lib/roo/spreadsheet.rb
:9:in `new'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/roo-2.0.0/lib/roo/spreadsheet.rb
:9:in `open'
```

**Comment by xjz19901211** [comment]
my fix https://github.com/xjz19901211/roo/commit/84ff5cd9d968ecef63d1621e53465972dd1832b2

but, here https://github.com/xjz19901211/roo/blob/master/lib/roo/excelx.rb#L93 already call FIle.basename

is_stream?(filename_or_stream)  return true?

**Comment by stevendaniels** [comment]
@xjz19901211 I don't quite understand your second comment, so I sent you some followup questions via email. Please reply when you get the chance.

**Comment by xjz19901211** [comment]
@stevendaniels I'm soryy, my English is poor...
anyway, [here](https://github.com/xjz19901211/roo/commit/84ff5cd9d968ecef63d1621e53465972dd1832b2) solved the problem  :  )

**Comment by pabloh** [comment]
@xjz19901211, could you provide a PR with the fix plus a test?.

**Comment by xjz19901211** [comment]
@pabloh @stevendaniels 
Just found out that the bug has disappeared in the 2.0.1

**Comment by xjz19901211** [comment]
This bug in https://github.com/roo-rb/roo/blob/v2.0.0/lib/roo/excelx.rb#L262
```
 @tmpdir = make_tmpdir(filename.split('/').last, options[:tmpdir_root])
```

: )
