### ISSUE TITLE
Problem when import xlsx -> Ole::Storage::FormatError - OLE2 signature is invalid

### ISSUE THREAD

**Issue by ciromine** [roo-rb/roo#227]
I use [Active importer](http://github.com/continuum/active_importer) a gem to import excel files. This gem use Roo. I created the issue in his page, but they said this problem is specific of Roo.

The error is:

```ruby
Ole::Storage::FormatError - OLE2 signature is invalid:
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:378:in `validate!'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:370:in `initialize'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:112:in `new'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:112:in `load'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:79:in `initialize'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:85:in `new'
  ruby-ole (1.2.11.8) lib/ole/storage/base.rb:85:in `open'
  spreadsheet (1.0.3) lib/spreadsheet/excel/reader.rb:1282:in `setup'
  spreadsheet (1.0.3) lib/spreadsheet/excel/reader.rb:140:in `read'
  spreadsheet (1.0.3) lib/spreadsheet/excel/workbook.rb:32:in `open'
  spreadsheet (1.0.3) lib/spreadsheet.rb:65:in `open'
  spreadsheet (1.0.3) lib/spreadsheet.rb:71:in `open'
  roo (1.13.2) lib/roo/excel.rb:40:in `block in initialize'
  roo (1.13.2) lib/roo/base.rb:565:in `block in make_tmpdir'
  /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
  roo (1.13.2) lib/roo/base.rb:564:in `make_tmpdir'
  roo (1.13.2) lib/roo/excel.rb:31:in `initialize'
  roo (1.13.2) lib/roo/spreadsheet.rb:17:in `new'
  roo (1.13.2) lib/roo/spreadsheet.rb:17:in `open'
  active_importer (0.2.5) lib/active_importer/base.rb:175:in `initialize'
  active_importer (0.2.5) lib/active_importer/base.rb:82:in `new'
  active_importer (0.2.5) lib/active_importer/base.rb:82:in `import'
.
.
.
```

But when I probed with xls files I don't have problem. I use:

'active_importer', '0.2.5'.
'rails', '~> 4.2.0'
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
Do you know what is the origin of this error, in other projects I never received this with xlsx files. Plus I tried with xlsx files created on linux (Libre Office and WPS office) and windows (Office 2013), greetings!

**Comment by simonoff** [comment]
Few things:

1) You using old version of roo
2) active_importer trying to use spreadsheet for open xlsx files what is wrong. So this is in any case issue of `active_importer`

**Comment by simonoff** [comment]
Yes, I checked this gem and inside it supported only 'xls'

**Comment by chrisccerami** [comment]
Thank you @ciromine for opening this issue, and @simonoff for your response. You saved me a ton of time in trying to debug the same issue.
