### ISSUE TITLE
Issue saving sheets in variables

### ISSUE THREAD

**Issue by iastazach** [roo-rb/roo#233]
I seem to be having an issue with assigning different sheets to different variables.  Every time I set a new sheet into a new variable it overwrites all my previous ones.  For example:

```
book = Roo::Spreadsheet.open('anyfile.xlsx')
sheet1 = book.sheet 0
sheet2 = book.sheet 1
```

After doing the above, `sheet1.row 1` and `sheet2.row 1` both return the exact same thing, no matter what; however, `book.sheet(0).row 1` and `book.sheet(1).row 1` return different values, as expected.

I'm a bit of a Ruby noob, so I may just not understand how this is supposed to work, but wanted to ask in case there is a legit issue.  I've tested multiple spreadsheets, and it does the same thing across all of them.

**Comment by simonoff** [comment]
Yes, because it resurn same book object.

**Comment by iastazach** [comment]
Great, thanks!

**Comment by simonoff** [comment]
It's only set default sheet not returning sheet itself.
