### ISSUE TITLE
`extension_for': uninitialized constant URI (NameError)

### ISSUE THREAD

**Issue by raysango** [roo-rb/roo#244]
Just starting to use the gem to open a xlsx file and I got the above error my code is below

require 'rubygems'
require 'roo'
file = Roo::Spreadsheet.open('sample_data.xlsx')
print file.info

I'm using rub v2.2.1p85, also I'm not sure why we need to require 'rubygems' but I found it on many issues as a solution

update when I add require 'uri' it will be able to access the file but do you know why?

**Comment by stevendaniels** [comment]
It looks like you found a bug. `lib/roo/spreadsheet.rb` should have a `require 'uri'` statement. URI is required because remote spreadsheet files can also be used. I guess in practice, URI gets pulled in by another gem like Rails. I'm working on a fix.
