### ISSUE TITLE
ArgumentError with underined class/module Spreadsheet:: 

### ISSUE THREAD

**Issue by Bivek** [roo-rb/roo#246]
ArgumentError: undefined class/module Spreadsheet:: while trying to upload an excel file with a hyperlink in it dowloaded from google spreadsheet.

**Comment by stevendaniels** [comment]
@Bivek Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by stevendaniels** [comment]
Since there has been no response in two weeks, I'm closing this issue.
