### ISSUE TITLE
need suggestions to debug Performance issues

### ISSUE THREAD

**Issue by atzorvas** [roo-rb/roo#251]
Hi, 
I noticed from yesterday that this one is **condionaly** terrible slow in my rails app: ```xls.cell(a, b)```
IIRC, the first time that I run the same code (days ago), I hadn't that "delay"

something else, maybe not-relative, but I don't remember having the same issue also, my tmp is flooded with roo_ files, each file shouldn't be removed after the .close?

    documents.each
      expression.scan(/[α-ωΑ-ΩA-Z][\d]+/).each do |s|
        a = s.scan(/\d+|[α-ωΑ-Ωa-zA-Z]+/)[0].el_to_en
        b = s.scan(/\d+|[α-ωΑ-Ωa-zA-Z]+/)[1].to_i
        val = xls.cell(a, b) # "conditionaly" slow part, only for the first time in each doc
        expression.gsub!(s, val.to_s)
      end
      xls.close
    end

[bundle list output](https://gist.github.com/atzorvas/c1514bec9c91d546de56)

any suggestions/ideas would be much appreciated,
thanks

**Comment by stevendaniels** [comment]
Could you provide a few more details? What spreadsheet type are you opening? How big is it (i.e. how many rows and columns?)?

I think the problem might be because Roo doesn't read any cell data until the first time a cell is accessed.  (That's the case when opening xlsx and ods files).

**Comment by atzorvas** [comment]
most of the files I'm opening with this itteration are xlsx, a few amount are xls
3 to 5 sheets, with average of 10 columns per sheet and rows from hundreds to thousands.

maybe it's better (? - in terms of speed) to store my excel files in a db, so I can get over this overhead

(or maybe I'll leave it as is, since it's working. delays aren't much of an issue since I'm calling only once this whole method)

**Comment by atzorvas** [comment]
@stevendaniels what about the .close method?
is there anything to "close" so it cleans the according folder in tmp?

**Comment by stevendaniels** [comment]
I'm not sure what the preferred behavior should be. 

@simonoff Should the `close`method remove the tmp folder and files that Roo creates when opening a spreadsheet?

**Comment by atzorvas** [comment]
@stevendaniels https://github.com/roo-rb/roo/blob/master/lib/roo/base.rb#L40-L44
close does exatcly that, something wrong on my side should cause the issue of the leftovers inside my /tmp.

also I'm closing this issue
