### ISSUE TITLE
NoMethodError: undefined method `extract' for nil:NilClass

### ISSUE THREAD

**Issue by Dimcha** [roo-rb/roo#254]
I am getting this error

```
Roo::Excelx.new("/tmp/gb.xlsx", packed: nil, file_warning: :ignore)
NoMethodError: undefined method `extract' for nil:NilClass
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:408:in `block in extract_sheets_in_order'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:403:in `each'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:403:in `each_with_index'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:403:in `extract_sheets_in_order'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:444:in `process_zipfile_entries'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:423:in `process_zipfile'
	from /home/dim/.rvm/gems/ruby-2.0.0-p647/gems/roo-2.1.1/lib/roo/excelx.rb:100:in `initialize'

```

Any ideas how to fix it?

**Comment by stevendaniels** [comment]
After a quick look, I think the issue is because your XLSX file is corrupt. Can you tell me how the file was created?

Specifically, it looks like you're XLSX file might be missing a sheet. Essentially, an XLSX file is a `zip` file with a specific directory structure. One of it's files lists the sheets the file contains.  The method `extract_sheets_in_order` extracts each of those sheets in order, but in your case, the zip file is missing that file. 

I will submit a fix soon, but in the meantime, try this patch.


    require 'roo'
    require 'roo/excelx'
    class Roo::Excelx
        def extract_sheets_in_order(entries, sheet_ids, sheets, tmpdir)
          sheet_ids.each_with_index do |id, i|
            name = sheets[id]
            entry = entries.find { |e| e.name =~ /#{name}$/ }

            Kernel.warn "This  sheet appears to be missing: name =>#{name}, sheet_id => #{id}" if entry.nil?
            next if entry.nil?

            path = "#{tmpdir}/roo_sheet#{i + 1}"
            sheet_files << path
            @sheet_files << path
            entry.extract(path) 
          end
       end
    end


Let me know if that solves your issue.

**Comment by Dimcha** [comment]
Sorry for delay. Coming back to that issue. Yes sorry, the problem is within another gem. The one that creates xlsx file seamusabshere/xlsx_writer

Sorry again, closing issue.

**Comment by CJKinni** [comment]
I ran across this same error with an xlsx file generated from a piece of software in my industry. I'm not sure what libraries it was using to generate the file, but I found that its 'names' contained a preceding "/".  I don't know how common this is, but here was my quick fix:

    class Roo::Excelx
        def extract_sheets_in_order(entries, sheet_ids, sheets, tmpdir)
          sheet_ids.each_with_index do |id, i|
            name = sheets[id]
            #Checking and fixing malformed names!
            if name[0] == "\/"
            	name = name[1..-1]
            end
            entry = entries.find { |e| e.name =~ /#{name}$/ }
    
            Kernel.warn "This  sheet appears to be missing: name =>#{name}, sheet_id =>#{id}" if entry.nil?
            next if entry.nil?
    
            path = "#{tmpdir}/roo_sheet#{i + 1}"
            sheet_files << path
            @sheet_files << path
            entry.extract(path) 
          end
        end
    end

This is the third time hitting this type of issue, so I figured I'd provide the little help I can to anyone else suffering through a similar issue.

Thanks!

**Comment by MatthiasEngh** [comment]
this was fixed in https://github.com/roo-rb/roo/commit/f1bc6e643a4d9af7934a41ae3f157796cf4de623 in case someone else like me is still running into this
