### ISSUE TITLE
Changing text value to float .xls, .xlsx and .ods

### ISSUE THREAD

**Issue by krzyh1989** [roo-rb/roo#256]
Hi,

I have problem with parsing Excel end OpenOffice files. For example I have row like this:

> 0 986 040 631 | 0 986 040 641 | 608 1271 3

In Excel or OpenOffice I set cell format to **text**.
After parsing I get this values:

> 986040631.0 | 986040641.0 | 60812713.0

Any Idea how to fix it?

**Comment by stevendaniels** [comment]
I need some more details to help understand the problem.
First, which version of Roo are you using?

Second, can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by krzyh1989** [comment]
I use Roo v2.1.1.
https://github.com/krzyh1989/roo_error 
CSV files works fine

**Comment by thotmx** [comment]
@krzyh1989 
Your code works correctly with the master branch from github.
Please clone this repository: https://github.com/thotmx/roo_error
(It's your code with minor changes).
I think the results are what you want.

**Comment by krzyh1989** [comment]
@thotmx Thanks! My fault I didn't try from github!

**Comment by stevendaniels** [comment]
I'll put out a new version of the gem later this week.

**Comment by vladra** [comment]
Just wondering if this was fixed since I got same problem
