### ISSUE TITLE
Issue while parsing the xlsx file in case of | character in the cells

### ISSUE THREAD

**Issue by naresh-uvision** [roo-rb/roo#257]
I have a .xlsx file in which in some cell which is not in first row there is a value like test1|test2|test3, in this case these values test1, test2 and test3 are referred as column names. Please check the issue.

**Comment by stevendaniels** [comment]
Thanks for reporting the issue. Which version of Roo are you using?

**Comment by stevendaniels** [comment]
I'm closing this issue. If someone notices a similar issue, please re-open with a gist sample.
