### ISSUE TITLE
How to get rows from a second table in the same spreadsheet with the same header?

### ISSUE THREAD

**Issue by THPubs** [roo-rb/roo#260]
In my spreadsheet, (I have attached a sample) I have two tables. Both have similar headings. When I run `xl.parse(:id => 'SKU Code')` it returns rows from the first table. But how to get data from the second table?

https://drive.google.com/file/d/0B_qbiPxuAyj7MTJkdms4M2M1Vm8/view?usp=sharing

**Comment by stevendaniels** [comment]
You need to switch to the other sheet.
 
    xl.default_sheet = xl.sheets.last
    xl.parse(:id => 'SKU Code')

**Comment by THPubs** [comment]
@stevendaniels Unfortunately it's in the same sheet!

**Comment by stevendaniels** [comment]
@THPubs I see what you mean. Unfortunately, Roo doesn't support such a capability. :sob:
