### ISSUE TITLE
Is there a row limit?

### ISSUE THREAD

**Issue by btrscott** [roo-rb/roo#262]
I have a spreadsheet with 5517 rows and it is reporting the the last row is 4896.  Is that a limit or should I be looking for something else?

**Comment by stevendaniels** [comment]
Do all of the rows in your spreadsheet have data? If they don't, then Roo is probably ignoring them due to  pad_cells option (See #249).

If that isn't the case, please let me know.

**Comment by btrscott** [comment]
My bad.  It's working.
