### ISSUE TITLE
Unrecoverable error read error with v2.2.0 - invalid value for Integer(): "#N/A"

### ISSUE THREAD

**Issue by jheilema-nerdery** [roo-rb/roo#269]
Hi y'all! Great gem, thanks for all your fantastic work on it!

I've got a bug, that was introduced between 2.1.1 and 2.2.0.

It only happens when attempting to access a worksheet that has the text "#N/A" in a cell because a specific lookup formula couldn't find a value. The script works as long as I don't attempt to access that particular sheet, using sheet.last_row. Downgrading to 2.1.1 makes it work again. 

Anonymized stack trace: 

ArgumentError: invalid value for Integer(): "#N/A"
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/cell/number.rb:23:in `Integer'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/cell/number.rb:23:in `create_numeric'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/cell/number.rb:13:in `initialize'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/cell.rb:49:in `new'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/cell.rb:49:in `create_cell'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:149:in `create_cell_from_value'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:101:in `block in cell_from_xml'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:90:in `cell_from_xml'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:189:in `block in extract_cells'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:187:in `map'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:187:in `extract_cells'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet_doc.rb:18:in `cells'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet.rb:18:in `cells'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet.rb:22:in `present_cells'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx/sheet.rb:58:in `last_row'
/.rvm/gems/ruby-2.2.2/gems/roo-2.2.0/lib/roo/excelx.rb:117:in `last_row'
/project/app/services/importers/production_data_importer.rb:23:in `last_row'
/project/app/services/importers/production_data_importer.rb:12:in `import'
/project/lib/tasks/integration.rake:19:in `block (3 levels) in <top (required)>'
/project/lib/tasks/integration.rake:13:in `each'
/project/lib/tasks/integration.rake:13:in `block (2 levels) in <top (required)>'

**Comment by stevendaniels** [comment]
Can you provide a gist with a spreadsheet that causes the issue?

**Comment by jheilema-nerdery** [comment]
I can, but not today - about to be busy for the evening. Will message tomorrow.

**Comment by jheilema-nerdery** [comment]
I created a gist with an example spreadsheet and the code that will trigger errors: https://gist.github.com/jheilema-nerdery/a1cd81d41abf1c484546

**Comment by stevendaniels** [comment]
This issue is caused by your cells with "#N/A" in your sheet are considered Number cells by Roo, so when Cell::Number calls `Integer('#N/A')` it raises an exception. Obviously, '#N/A' is not a number. 

I'll have to think about the best way to handle this situation. Should I create a special case for this type of cell? Or should there be a `Cell::Error` type for these types of cells.

The following cells are also possible errors.
#N/A #REF! #NAME? #DIV/0! #NULL! #VALUE! #NUM!

**Comment by jheilema-nerdery** [comment]
That's unclear. In my use case, throwing a Cell::Error exception is a possible good solution; I'd have to update my code to catch it though. I think previously it was just returning the '#N/A' text as you have in this temporary fix. Maybe throwing the exception could be part of the roadmap for the next 'breaking changes' release?

**Comment by stevendaniels** [comment]
I didn't explain myself well and Cell::Error is probably a really confusing name. Cell::Error wouldn't be an exception. It would be a cell type to handle error states like "#N/A" and "#DIV/0".

**Comment by jheilema-nerdery** [comment]
Oh! I see! So instead of Cell::Number, basically? And have it's own handling for interpreting the datatype for Ruby. Makes sense. 

It might make sense to throw a named exception when getting the value of the cell, since Cell::Error isn't going to have a value that's going to work for most applications; either that, or return `nil` or an empty string or something. 

I'd rather have an exception there that I can catch, since other non-error cells could also be empty, and it'd be good to distinguish between them. An error state in a cell is a situation where want different handling than just `nil`, since it means my original data set is bad. I want to create an error message for that situation, and tell the user to fix their spreadsheet (for that cell, on that row, etc).

**Comment by kuldeepaggarwal** [comment]
I differ with the opinion @jheilema-nerdery, but before my opinion a big Thanks for this great Gem and its creator. I would rather in the favour of having different type, `Cell::Error` and having the error value corresponding to either of the values `#N/A, #REF!, #NAME?, #DIV/0!, #NULL!, #VALUE!, #NUM!` as it will allow the end user,like in my case I will show the user who uploaded the file a proper error message for invalid cells, to take appropriate step to handle the errors for a particular cell instead of raising error for whole file.

**Comment by deltreey** [comment]
I also see this error with values like `1E4`

**Comment by ajsharp** [comment]
I'm having a similar issue with cells containing `#N/A`, though, it's worth mentioning that these cells contain VLOOKUP's that fail. Maybe excel considers any cells with a formula to be numeric?

I would vote for having the library simply returning the `#N/A` value as text as a normal value. Returning `Cell::Error

**Comment by kuldeepaggarwal** [comment]
@ajsharp I was suggesting the type of data would be `Cell::Error` which will return the error'ed value, like: `[#N/A, #REF!, #NAME?, #DIV/0!, #NULL!, #VALUE!, #NUM!]`

**Comment by ajsharp** [comment]
@kuldeepaggarwal Yea, my concern with that is accessing the underlying value in a consistent manner with the other types of data. Otherwise, every time you access data from a cell, you need to do a check to make sure it's not a `Cell::Error`, which may as well be a real exception. Hopefully that makes sense.

**Comment by stevendaniels** [comment]
I've thought about this issue for a while now and I agree with @ajsharp. Adding Cell:Error would complicate usage quite a bit. And raising an error would break things for a lot of unsuspecting users.

I'll be adjusting #273 so that it also deals with those other possible errors.

**Comment by kuldeepaggarwal** [comment]
@stevendaniels Thanks for quick fix. Cheers :beer:

**Comment by stevendaniels** [comment]
Published Roo 2.3.0 which includes these fixes.
