### ISSUE TITLE
IOError: closed stream when using StringIO in Ruby 1.9.3

### ISSUE THREAD

**Issue by agrimm** [roo-rb/roo#271]
When parsing a StringIO object of an xlsx spreadsheet in Ruby 1.9.3, I get the following error:

     IOError:
       closed stream

This doesn't happen with recent versions of Ruby.

There's a test failure in https://travis-ci.org/roo-rb/roo/jobs/89364759 of the test `TestRoo#test_open_stream` when run under Ruby 1.9.3 (based on pull request #270 ) that looks identical:

      1) Error:
    TestRoo#test_open_stream:
    IOError: closed stream
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/input_stream.rb:117:in `seek'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/input_stream.rb:117:in `get_io'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/input_stream.rb:52:in `initialize'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:498:in `new'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:498:in `get_input_stream'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:583:in `block in create_file'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `open'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `create_file'
        /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rubyzip-1.1.7/lib/zip/entry.rb:154:in `extract'
        /home/travis/build/roo-rb/roo/lib/roo/excelx.rb:331:in `extract_worksheet_rels'
        /home/travis/build/roo-rb/roo/lib/roo/excelx.rb:389:in `process_zipfile_entries'
        /home/travis/build/roo-rb/roo/lib/roo/excelx.rb:369:in `process_zipfile'
        /home/travis/build/roo-rb/roo/lib/roo/excelx.rb:45:in `initialize'
        /home/travis/build/roo-rb/roo/test/test_roo.rb:2080:in `new'
        /home/travis/build/roo-rb/roo/test/test_roo.rb:2080:in `test_open_stream'

For what it's worth, I ran rubyzip's unit tests under Ruby 1.9.3 on my local machine, and none of them failed.

**Comment by stevendaniels** [comment]
Unfortunately, Roo doesn't necessarily support Ruby 1.9.3.
