### ISSUE TITLE
`ArgumentError` when opening xlsx spreadsheet

### ISSUE THREAD

**Issue by wvengen** [roo-rb/roo#272]
Roo chokes on [this xlsx file](http://filebin.ca/2Lxyy0ntrymc), generated by [SpreadsheetGear](https://www.spreadsheetgear.com/) 6.0.3.210.

```
ArgumentError - ArgumentError:
  roo (2.2.0) lib/roo/utils.rb:23:in `split_coord'
  roo (2.2.0) lib/roo/utils.rb:9:in `split_coordinate'
  roo (2.2.0) lib/roo/excelx/sheet_doc.rb:42:in `block in each_cell'
  nokogiri (1.6.6.2) lib/nokogiri/xml/node_set.rb:187:in `block in each'
  nokogiri (1.6.6.2) lib/nokogiri/xml/node_set.rb:186:in `each'
  roo (2.2.0) lib/roo/excelx/sheet_doc.rb:41:in `each_cell'
  roo (2.2.0) lib/roo/excelx/sheet.rb:97:in `cells_for_row_element'
  roo (2.2.0) lib/roo/excelx/sheet.rb:34:in `block in each_row'
  roo (2.2.0) lib/roo/utils.rb:74:in `block in each_element'
  nokogiri (1.6.6.2) lib/nokogiri/xml/reader.rb:107:in `each'
  roo (2.2.0) lib/roo/utils.rb:72:in `each_element'
  roo (2.2.0) lib/roo/excelx/sheet_doc.rb:34:in `each_row_streaming'
  roo (2.2.0) lib/roo/excelx/sheet.rb:31:in `each_row'
  roo (2.2.0) lib/roo/excelx.rb:271:in `each_row_streaming'
```

I heavily edited the file to remove sensitive data, but it still shows the problem.
Opening it with Libreoffice and saving a copy as xlsx lets roo parse it.

**Comment by stevendaniels** [comment]
Hi. I took a look at the spreadsheet you provided. It looks like SpreadsheetGear creates uses non-standard xml for cells.

Here's what your sheet's xml looked like:
    
    <sheetData>
      <row ht="15" customHeight="1" s="12" customFormat="1">
        <c s="4" t="s">
          <v>1</v>
        </c>
        <c s="4" t="s">
          <v>1</v>
        </c>
        ...
      </row>
    </sheetData>


The cell's are missing the `r` attribute which is used as a reference to the cell's location. According to "Ecma Office Open XML Part 1", the reference attribute is required for cells (see the bottom of 3863). So the XML data should look like this.

    <sheetData>
      <row ht="15" customHeight="1" s="12" customFormat="1">
        <c s="4" t="s" r="A1">
          <v>1</v>
        </c>
        <c s="4" t="s" r="A2">
          <v>1</v>
        </c>
        ...
      </row>
    </sheetData>

OpenOffice is smart enough to be able to open this file properly and save it properly. Unfortunately, Roo doesn't have the ability to fix non-standard xlsx documents. You should contact the maker of Spreadsheet Gear.

References: [SpreadsheetML Cell Class](https://msdn.microsoft.com/EN-US/library/office/documentformat.openxml.spreadsheet.cell.aspx)

**Comment by wvengen** [comment]
Looking in the OOXML XSD, I can see it's indeed a required attribute. Thanks for your quick reply, even though it wasn't in issue on roo :+1:
