### ISSUE TITLE
How to read embedded images in an xlsx?

### ISSUE THREAD

**Issue by airblade** [roo-rb/roo#274]

**Comment by stevendaniels** [comment]
I don't think Roo currently has the ability to read an image in an xlsx. Could you provide me with a link to  an xlsx file with an image so that I could work on adding that functionality?

**Comment by airblade** [comment]
Here you go:

[bar.xlsx](https://github.com/roo-rb/roo/files/31821/bar.xlsx)

**Comment by donv** [comment]
Hi!

Any progress on this one?

**Comment by stevendaniels** [comment]
Related to #317?

**Comment by stevendaniels** [comment]
Merged with #414
