### ISSUE TITLE
Memory not freed after last_row calculation.

### ISSUE THREAD

**Issue by lucianasorbelli** [roo-rb/roo#275]
Hi ! Here 's my problem, I'm trying to parse huges excel files (about 500.000 rows or even more), and I found that after calculation, last_row method generates about 3GB of extra memory usage, which is not freed up after the method call.

This makes further processing impossible, which initially means that somewhere over last_row trace some objects are instantiated but not derreferenced later.

Any idea where that could be?

I also tried to converting to CSV, wich (according to google) seems to be lighter, but there are not good enough gems out there to do this (most of them depend on Roo, anyway).

I would appreciate any solution/suggestion about this issue.

Thanks.

**Comment by simonoff** [comment]
@lucianasorbelli are you using streaming? roo supporting streaming read of xlsx files.

**Comment by lucianasorbelli** [comment]
@simonoff , not yet, the thing is that I need to get the total rows to know how many backgroundWorkers are needed to run in parallel to parse a file with 300K+ rows. 

I'm following  https://github.com/roo-rb/roo/issues/179. The same problem.

Thank you very much for answering.

**Comment by stevendaniels** [comment]
@simonoff Is it possible to use `SheetDoc.extract_dimensions` for determining the last_row?

**Comment by IgorJorobus** [comment]
Reporting same issue here. Working with a *.xlsx of 16 MB, ~100K rows. The process swallows around 2GB then crash due to NoMemoryError.

**Comment by stevendaniels** [comment]
This issue was also analyzed in #322, but using `SheetDoc.extract_dimensions` breaks functionality. 

If you need to get the last_row quickly, I recommend extracting that information from the `SheetDoc.dimensions` method.

**Comment by embs** [comment]
@stevendaniels would you please clarify what do you mean by

>  using `SheetDoc.extract_dimensions` breaks functionality.

What functionality does it break?

Thanks!
