### ISSUE TITLE
Seeding database in rails with roo gem

### ISSUE THREAD

**Issue by nbajwa** [roo-rb/roo#279]
While using this gem for rails I found that the documentation was partly misleading because my database would not recognize the file with the given upload instructions. I had to amend my code so that the file was found in relation to the root of the app, I used ex= Roo::Excel.new(Rails.root.join('db', 'excel.xlsx')). I think mentioning this might be a great addition to the documentation for this already awesome gem!

**Comment by stevendaniels** [comment]
Thanks for the suggestion. Can you elaborate on which lines of the documentation where misleading? Thanks.

**Comment by stevendaniels** [comment]
I'm marking this issue as closed. Please feel free to re-open to elaborate on the misleading parts of the documentation.
