### ISSUE TITLE
Positive floats less than 1 are being left in exponential form in Excel files

### ISSUE THREAD

**Issue by nshoes** [roo-rb/roo#284]
Hello! I came across a bug today and am curious if you guys have heard of it, if there is a fix already, or can give me some insight into something I am doing wrong. I am using version `2.3.0`.

As the title suggests, when parsing an `xlsx` file and when a cell has a positive value less than zero (`.002` in my case) I get the error `invalid value for Integer(): "2E-3"`. After some digging, I found that my original float was being converted into exponential form and then blowing up [in the Number class](https://github.com/roo-rb/roo/blob/master/lib/roo/excelx/cell/number.rb#L25). Also seems that this is an Excel issue, because when I convert the file to a CSV in Numbers it works.

Thoughts?

**Comment by stevendaniels** [comment]
Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by stevendaniels** [comment]
#288 solves this issue.

**Comment by nshoes** [comment]
Sweet!!!
