### ISSUE TITLE
unhandled onecell-class Fixnum in cell_to_csv

### ISSUE THREAD

**Issue by InteNs** [roo-rb/roo#285]
https://github.com/roo-rb/roo/blob/master/lib/roo/base.rb#L700-L714
is there a specific reason for this?

**Comment by stevendaniels** [comment]
I don't think there's a specific reason for this issue. Did you run into that error?

**Comment by InteNs** [comment]
Yes, after updating from 2.1 to 2.3 this error started happening on a test with a lot of formulas in its sheet.

**Comment by stevendaniels** [comment]
Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by InteNs** [comment]
here's the [gist](https://gist.github.com/InteNs/884a347acb97f644a25a)

**Comment by InteNs** [comment]
@stevendaniels Is there something wrong with my PR? there hasn't been any respone yet.
