### ISSUE TITLE
Wrong cell types

### ISSUE THREAD

**Issue by vladra** [roo-rb/roo#286]
I've configured all cells in my xlsx file as TEXT type, so I assume that `celltype` method should return `string` for me.

But it's returning `float` for number values. Is this a bug or am I doing something wrong?

Thanks for help!

**Comment by stevendaniels** [comment]
Assuming you're using the most common version of Roo (2.3.0), then you can use the `formatted_value` method to return a `String`.

**Comment by vladra** [comment]
I'm using Spreadsheet class to extract values, because it has columns mappings feature.

But before parsing file, I was trying to check if all fields are in TEXT format (to return error to user asking him to fix this). I've adjusted xlsx accordingly, but `celltype` method returns not real cell type (float instead of string)

**Comment by stevendaniels** [comment]
Could you please create a gist and refer to it in an issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c)). Here are some instructions for creating such a gist.

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.
