### ISSUE TITLE
Comments are taken from the wrong sheet

### ISSUE THREAD

**Issue by ibrahimtencer** [roo-rb/roo#291]
For some reason, the #comment method on XLSX spreadsheets sometimes takes comments from the sheet just after the expected one. I'm not sure why this happens, and it happens sporadically. It seems to me like the sheet number should be passed rather than the sheet name, by the way (what if two sheets have the same name?). The comments for the first sheet are also apparently impossible to get - let me know if there is a workaround to do this please.

**Comment by stevendaniels** [comment]
Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by stevendaniels** [comment]
I don't have enough information to investigate this issue. I'm closing it. Please feel free to re-open the issue if you add a gist. Thanks.
