### ISSUE TITLE
Roo (2.1.0) not compatible with Axlsx (2.0.1)

### ISSUE THREAD

**Issue by al3izz** [roo-rb/roo#296]
When you try to use Roo 2.1.0 and Axlsx 2.0.1 at the same time, you get a rubyzip dependency conflict.
Axlsx depends on Rubyzip 1.0.0, while Roo depends on Rubyzip >= 1.1 && < 2.0

This is a bummer for people who want to be able to import and export with the latest technologies. In my situation, I'm forced to use the latest version of Axlsx (2.0.1). In order for me to use this with Roo at the same time, due to the Rubyzip conflict, I must use Roo 1.13.2.

Does anyone have any ideas on how we can use the latest versions of both gems at the same time?
Thanks.

**Comment by stevendaniels** [comment]
Try using the master branch for axlsx, it uses rubyzip v1.1. 

    source 'https://rubygems.org'

    gem 'roo', '~> 2.3.1'
    gem 'axlsx', git: 'https://github.com/randym/axlsx.git'

I've also added a comment on an existing Axlsx issue: https://github.com/randym/axlsx/issues/419

**Comment by matiasmenares** [comment]
@stevendaniels Thanks a lot!
