### ISSUE TITLE
Does roo support creating Excel template (.xltx) files?

### ISSUE THREAD

**Issue by russellsilva** [roo-rb/roo#305]
I want to create a [.xltx Excel template file](https://support.office.com/en-us/article/Save-a-workbook-or-worksheet-as-a-template-58c6625a-2c0b-4446-9689-ad8baec39e1e). Is this possible using roo?

**Comment by stevendaniels** [comment]
No. Roo is for reading spreadsheet files, not writing them. Perhaps a library like https://github.com/randym/axlsx will have similar functionality.
