### ISSUE TITLE
Reading from :binary column in database?

### ISSUE THREAD

**Issue by mvarrieur** [roo-rb/roo#307]
I have a database table for storing tiny excel blobs into a binary column, and I'm hoping to read them with Roo in a delayed job and parse them, is that possible?

Here is my schema for the table, I have the file stored inside the column properly already, hoping I can read it straight into Roo somehow without having an actual file path?

    create_table "documents", force: :cascade do |t|
        t.string   "filename"
        t.string   "content_type"
        t.binary   "file_contents"
        t.datetime "created_at",    null: false
        t.datetime "updated_at",    null: false
      end

**Comment by akshah123** [comment]
Temporary work around would be to create a temp file and pass that into the class.

**Comment by stevendaniels** [comment]
Did you try just passing the blob contents as a stream?

`Roo::Spreadsheet.open(stream, options)`

**Comment by r-zia** [comment]
do it like this
  def read_file(blob_id)
    blob = ActiveStorage::Blob.find(blob_id)
    raise 'File not Found' if blob.nil?
    stream = StringIO.new(blob.download)
    @xlsx = Roo::Spreadsheet.open stream, extension: :xlsx
  end
