### ISSUE TITLE
determine hidden sheet / cell

### ISSUE THREAD

**Issue by halcjames** [roo-rb/roo#309]
is it possible to determine if a cell or a sheet is hidden? 

thanks!
James

**Comment by stevendaniels** [comment]
There's isn't a good way to determine if a sheet is hidden. There is no way to determine if a cell is hidden.

If you opened 2 copies of the spreadsheet, you could figure out which sheets are hidden

    all_sheets = Roo::Spreadsheet(path).sheets
    visible_sheets = Roo::Spreadsheet(path, only_visible_sheets: true).sheets
    hidden_sheets = all_sheets - visible_sheets
