### ISSUE TITLE
Off-by-one error for xlsx time cells 12:34:13 PM

### ISSUE THREAD

**Issue by mlrus** [roo-rb/roo#310]
https://gist.github.com/mlrus/32fef531c69d74c2e94d377456e75003

The value of xlsx.cell(1,1) is off-by-one for cell 12:23:13 PM. Methods #to_yaml and #to_csv report the incorrect value 12:34:12, and method #cell reports the incorrect 45252 instead of 45253.

The xlsx cell representation of 12:23:13 PM is 0.523761574074074 (days). On transforming to seconds the floating-point value should be rounded for consistency with the cell's external value, 12:23:13 (45253).

**Comment by stevendaniels** [comment]
I'm looking into the issue.

**Comment by mlrus** [comment]
Is there a bug fix for this issue?
