### ISSUE TITLE
Excel date cells do not receive current time zone

### ISSUE THREAD

**Issue by hoenth** [roo-rb/roo#311]
When opening an Excel file that contains date cells, the values are converted to DateTime objects with 0 offset, regardless of the time zone set for the request/application. 

Would you consider the following change to the excelx datetime.rb file
from:
````
        def create_datetime(base_date, value)
          date = base_date + value.to_f.round(6)
          datetime_string = date.strftime('%Y-%m-%d %H:%M:%S.%N')
          t = round_datetime(datetime_string)

          ::DateTime.civil(t.year, t.month, t.day, t.hour, t.min, t.sec)
        end
````

to
````
        def create_datetime(base_date, value)
          date = base_date + value.to_f.round(6)
          datetime_string = date.strftime('%Y-%m-%d %H:%M:%S.%N')
          t = round_datetime(datetime_string)

          ::DateTime.civil(t.year, t.month, t.day, t.hour, t.min, t.sec, t.zone.utc_offset/60/60).to_s)
        end
````

Since t is created with Time.now, it should, by default, use the correct offset. 

DateTime.civil's last argument is the offset in hours in a string (i.e. "-4").

**Comment by stevendaniels** [comment]
I have to look into this a bit further. I suspect there is a timezone value somewhere that roo isn't taking into consideration. Can you provide a sample xlsx spreadsheet that exhibits the issue (in a gist)?

**Comment by hoenth** [comment]
Interestingly, it turned out that this solution did not work for me either, as the Time value continued to use the system time zone and not the Rails time zone (Time.zone = "[time zone string]") which was set prior to calling Roo::Excelx.new(file_path). Locally for me, this was EDT, but on our servers, it is UTC. I haven't had the opportunity to investigate why that is. I believe any spreadsheet with a column formatted to include date and time will exhibit this issue, where the offset will always be 0 without the change I have suggested, and will be the system offset with my changes.

**Comment by stevendaniels** [comment]
I've looked into this issue more. Here a few things I noticed:
1. You're solution seems to be based on ActiveSupport.
2. I see the need for this functionality, but I can't think of an implementation that would be ActiveSupport agnostic (since Roo doesn't depend on ActiveSupport).
3. I think the code you originally listed has an error. The following worked for me:

        def create_datetime(base_date, value)
          date = base_date + value.to_f.round(6)
          datetime_string = date.strftime('%Y-%m-%d %H:%M:%S.%N')
          t = round_datetime(datetime_string)
          binding.pry

          # Time.zone requires active_support/time and the Time.zone should be set beforehand.
          ::DateTime.civil(t.year, t.month, t.day, t.hour, t.min, t.sec, (Time.zone.utc_offset/ 60 / 60))
        end

Have you tried the following:

```
cell = Cell::DateTime.new(args)
cell.value.in_time_zone
```

**Comment by hoenth** [comment]
@stevendaniels - Thanks for your reply. 
Did you find that your change would pick up the Rails time zone and not the servers time zone when they are different?

I haven't tried you second suggestion, but can look into it. 

I took a different tack. After reading a row, I run
````
row = set_zone_for_date_fields(row)
````

````
def set_zone_for_date_fields(data)
  data.each do |k,v|
    data[k] = Time.zone.local_to_utc(v) if v.is_a?(DateTime) or v.is_a?(Time)
  end
end
````

This obviously slows the process of reading the records, but is working.

**Comment by stevendaniels** [comment]
I'm closing for now. If you add a gist that demonstrates the issue, please reopen and I will look into the situation further.
