### ISSUE TITLE
Excel files with dedicated Chart sheets cannot be opened using roo

### ISSUE THREAD

**Issue by akshah123** [roo-rb/roo#312]
If the excel file has a dedicated sheet for charts, trying to open them results in following error:

`
Zip::DestinationFileExistsError: Destination '/tmp/roo_chart_sheet_problem.xlsx20160413-24980-1q8h6gp/roo_rels1' already exists
from gems/ruby-2.2.0/gems/rubyzip-1.2.0/lib/zip/entry.rb:572:in 'create_file'
`

The problematic example file is attached.  

[chart_sheet_problem.xlsx](https://github.com/roo-rb/roo/files/217958/chart_sheet_problem.xlsx)

**Comment by stevendaniels** [comment]
This issue is caused by an error in `Roo::Excelx#process_zipfile_entries`. The `chartsheets/sheet1.xml` gets extracted before the `worksheets/sheet1.xml` file.

The quick fix I tried broke some tests, so I will need to spend some time to figure out how best to fix this issue.

**Comment by stevendaniels** [comment]
@akshah123  Thanks for the sample file. Roo will ignore now ignore the chart sheets in a spreadsheet.
