### ISSUE TITLE
to_csv

### ISSUE THREAD

**Issue by vortx** [roo-rb/roo#313]
I had to change the method to_csv, to show the ability to change the delimiter and completed the method that unload all the sheets in one file, you might want to include it in the main gem, as it is necessary and frequent methods.

**Comment by stevendaniels** [comment]
Sounds awesome @vortx. Could you make a PR?

**Comment by vortx** [comment]
> it gave me to install a separator:

  **def to_csv(filename = nil, separator)**
    sheet = default_sheet
    if filename

> and so I supplement the file with all the sheets As Read:

     ** File.open(filename, 'a+') do |file|**

> and so I use your wonderful gem:

 xls = Roo::Excel.new(filename)
           File.open("#{filename}.csv",'w')
           xls.sheets.each_with_index do |name, index|
           xls.default_sheet = xls.sheets[index]
           xls.to_csv("#{filename}.csv",";")

As you have noticed I have to continually ocheschat Fail before filling it, but I'll be back later to this question :)
