### ISSUE TITLE
only_visible_sheets still shows hidden sheets

### ISSUE THREAD

**Issue by halcjames** [roo-rb/roo#314]
Does roo also skips the sheet that are tagged as "VeryHidden"? I have a workbook with a lot of hidden sheets and they are protected, I wanted to skip those using the code below yet it still shows up.

`Roo::Spreadsheet.open(template, { only_visible_sheets: true } )`

**Comment by stevendaniels** [comment]
Can you create a gist for this issue (Sample gist: https://gist.github.com/stevendaniels/98a05849036e99bb8b3c)? 

Here are some instructions for creating such a gist. 

1. Create a gist (https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by stevendaniels** [comment]
Please reopen with an appropriate gist that demonstrates the issue.
