### ISSUE TITLE
How do I get date value in .xslx to string ? 

### ISSUE THREAD

**Issue by jsnick** [roo-rb/roo#321]
in Mac .xlsx (Microsoft Excel),
I put "2011.1.11" into cell.
And roo gem read that excel file and get it.
The value is 40554, Fixnum.
How do I get original string value. "2011.01.11" ?
("2013.3.11" => 41344)
- roo gem (2.4.0)
- I used Roo::Excelx.new("path/to/file"), .sheet(), and .row() to get the value.
  (using .cell() is same) 
- inspect that value

`#<Roo::Excelx::Cell::Number:0x007ff95d9da9c8 @cell_type=[:numeric_or_formula, ""], @cell_value="40554", @coordinate=#<Roo::Excelx::Coordinate:0x007ff95d9dae50 @column=7, @row=5>, @format="", @formula=nil, @link=false, @style=2, @type=:float, @value=40554>,`

**Comment by stevendaniels** [comment]
@jsnick Please create a gist for this issue (Sample gist: https://gist.github.com/stevendaniels/98a05849036e99bb8b3c).

Here are some instructions for creating such a gist. 

1. Create a gist (https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by victorhazbun87** [comment]
I have the exact same issue. How can we get original value from rows?

**Comment by dan-corneanu** [comment]
Does this cell have a custom format associated with it by any chance?

I found that if styles.xml (inside the xlsx file) has white spaces between the `<xf />` elements, roo will not parse it properly and 
```ruby
     def extract_num_fmt_ids
        doc.xpath('//cellXfs').flat_map do |xfs|
          xfs.children.map do |xf|
            xf['numFmtId']
          end
        end
      end
```
will end up reading all blank text nodes between `<xf />` elements. From now on all style refs in the sheet will fail to resolve properly.

I'll come up with a gist to demonstrate this.

**Comment by dan-corneanu** [comment]
Here is a gist that demonstrates the issue
https://gist.github.com/dan-corneanu/1158e53c176a01bf7ac997b4a5746f1f

The only difference between the two xlsx files is that I have introduced some new lines in the `styles.xml` file.

**Comment by dodo121** [comment]
Hi guys, are you planning to add a feature for skipping reading excel cell formatting?. I (and some people over the internet) would like to have the ability to just skip reading formatting and be able to use plain string, for example read "05.02" as a string over a date.

I'm thinking about trying to add this feature, but I'm not sure if someone is not working on this.
