### ISSUE TITLE
Why first_row and last_row are inefficient.

### ISSUE THREAD

**Issue by MyklClason** [roo-rb/roo#322]
There are two reasons for this and I propose solutions for both. Here is how they are both implemented:

    @first_row ||= present_cells.keys.map { |row, _| row }.min
    @last_row ||= present_cells.keys.map { |row, _| row }.max

And here is present_cells:

    @present_cells ||= cells.select { |_, cell| cell && !cell.empty? }

The first issue is that both `.select` and `.map` create an array of all cells. The issue may be even deeper than this and `cells` could be doing the same thing and loading them all into memory at once.

Seems like these methods should be iterating over the rows (via say `rows.each`) and recording the first/last non-empty one.

This suggests the second issue. In many cases, there are clear start/end to the data. The first X rows can be skipped and the last Y rows can be skipped. This means that a type of binary search (implemented via an flag in the method, as you have to know a bit about the data before you can be sure this is a valid approach) can be used to more efficiently handle this. Last example (first works much the same, but is expected to be faster).

If row 15 is the last nonempty row and you start looking at row 1, it looks like this:

    row(1) => nonempty => higher
    row(2) => nonempty => higher
    row(4) => nonempty => higher
    row(8) => nonempty => higher
    row(16) => nonempty => higher
    row(32) => nonempty => higher
    row(64) => nonempty => higher
    row(128) => empty => higher

At this point you can just do a standard binary search over rows 64 to 128 to find the last nonempty row. For first_row, same thing, but the example would have `empty` and `nonempty` switched. A futher optimization would be only look at a specific column (say you know that all of the values in column 5 should be nonempty).

Overall, I see a lot of use of `map` in the code which creates an array and it may be better to use an iterator in many cases.

**Comment by stevendaniels** [comment]
There's actually a much faster method to get the first/last_row of a sheet, e.g.:

```ruby
def last_row
  dimension = @sheet.dimensions.split(":").last
  Roo::Utils.split_coordinate(dimension).first
end
```

But this method doesn't take into account empty rows/cells. Also, as written, the method would break functionality. 😢
