### ISSUE TITLE
How to get ORIGINAL values as String from Roo::Excelx rows

### ISSUE THREAD

**Issue by victorhazbun87** [roo-rb/roo#339]
I want to know how to get the values of each row as "String" from an Excelx file.

https://gist.github.com/victorhazbun87/40c7ecf26d0479b914303b86f34f472f

My Excelx file content looks like this:
A                    | B        | C
07:00:00 AM | Text | 08/01/2016

I expect the row to return:
         
    ["07:00:00 AM", "Text", "08/01/2016"]

but it is returning:

    [25200, "Text", Mon, 01 Aug 2016]

**Comment by stevendaniels** [comment]
use `cell.formatted_value`
