### ISSUE TITLE
README

### ISSUE THREAD

**Issue by sleeptillseven** [roo-rb/roo#34]
I feel a bit uncomfortable with the Documentation. If you're open for a proposal, give me some time and I'll try to do something. Maybe be some text reformatting will do.

Disclaimer: this issue is not intended as a personal insult. The gem is great and save's me tons of tears with other painful gems.

**Comment by stevendaniels** [comment]
I recommend closing this issue. Updates to documentation can be submitted with a pull request.

**Comment by stevendaniels** [comment]
@simonoff No response after 4 weeks. Please close this issue.
