### ISSUE TITLE
Basic authentication for URLS

### ISSUE THREAD

**Issue by victorhazbun87** [roo-rb/roo#341]
While trying to open Mailgun incoming emails attachments I found that they require basic authentication in order to actually open the attachments from the urls:

This is a real attachment url (XLS file)
   
"https://so.api.mailgun.net/v3/domains/mai.dockstarhq.com/messages/eyJwIjpmYWxzZSwiayI6ImUzZTM0ZjZmLWNmMTAtNGZmZS05NGU0LWNjNTgzYmYzYTZiOCIsInMiOiJiMDBjMmNlZGE2IiwiYyI6InNhb3JkIn0=/attachments/0"

By using the Roo::Spreadsheet class:

    Roo::Spreadsheet.open("https://so.api.mailgun.net/v3/domains/mai.dockstarhq.com/messages/eyJwIjpmYWxzZSwiayI6ImUzZTM0ZjZmLWNmMTAtNGZmZS05NGU0LWNjNTgzYmYzYTZiOCIsInMiOiJiMDBjMmNlZGE2IiwiYyI6InNhb3JkIn0=/attachments/0", extension: :xls)

RuntimeError: could not open https://so.api.mailgun.net/v3/domains/mai.dockstarhq.com/messages/eyJwIjpmYWxzZSwiayI6ImUzZTM0ZjZmLWNmMTAtNGZmZS05NGU0LWNjNTgzYmYzYTZiOCIsInMiOiJiMDBjMmNlZGE2IiwiYyI6InNhb3JkIn0=/attachments/0

What I can do in order to make it work? Please help me!

**Comment by stevendaniels** [comment]
In this case, I would suggest downloading the file with basic authentication and then using Roo to process it.
