### ISSUE TITLE
Unfork

### ISSUE THREAD

**Issue by sandstrom** [roo-rb/roo#351]
This is a great project and gem! 

To make it more obvious that this is the canonical repository I'd suggest unforking from pivotal-benchmark/roo. To unfork, simply contact Github support and explain that the other repo is stale/old and that you want to unfork.

It will help new people understand that this is the right repo for `roo`

**Comment by stevendaniels** [comment]
@simonoff, @Empact : You're the owners of this repo, so you'll have to contact Github.

**Comment by stevendaniels** [comment]
I've contacted github about this. Hopefully, we'll hear something soon.
