### ISSUE TITLE
Inconsistent Col Length in CSV Fails

### ISSUE THREAD

**Issue by bomberby** [roo-rb/roo#375]
After upgrading to 2.7.0, a service we've been using stopped working:

We are opening a CSV file generated by a third party, the first line contains meta-data, second line is headers, and third onward is the data itself.

Because the meta-data width is shorter than the data and roo is assuming the column_count according to first line, none of the data that is past these columns are accessible, making the service unusable.

**Comment by stevendaniels** [comment]
Could you provide a sample of the CSV that's giving you issues.

**Comment by bomberby** [comment]
A CSV as simple as 
```
1,2,3
1,2,3,4,5
```
When opening in it on roo 2.7.0
`csv.row(1) => ["1", "2", "3"]` : as expected
`csv.row(2) => ["1", "2", "3"]` : 4 and 5 are not there

On 2.6.0
`csv.row(1) => ["1", "2", "3", nil, nil]`
`csv.row(2) => ["1", "2", "3", "4", "5"]`

**Comment by kakoni** [comment]
It fails because `set_column_count` in `csv.rb` assumes that first line in csv file sets the maximum column length (https://github.com/roo-rb/roo/blob/master/lib/roo/csv.rb#L109)
