### ISSUE TITLE
Importing 683 Excel Record

### ISSUE THREAD

**Issue by ksugiarto** [roo-rb/roo#39]
I'm sorry I don't know if this is an issues/bug or just mistake I done, but I'm kind of sure that I have try everything to analyze this case, so, I'm sorry if I wrote on the wrong place.

The case, I have 683 records that I want to imported to my application. It's about 3 or 4 times (in not sequential)  I try to imported those record, but always make my local server like dead lock. I done trying imported 25 records, 100 records, 500 records, 600 records, even 682 records all done well, but from 683 records it turn like that.

I done trying to swap the data, for example I have data (1, 2, 3, 4, 5, 6, 7 , 8, 9, 10), I done trying with data (1, 2, 3) then (1, 2, 3, 4, 5, 6, 7) or (4, 5, 6, 7, 8, 9, 10) or (3, 6, 7, 10) etc. But it all resulting the same result. Total rows <= 682 all perfect but from 683 that always make my (local) server (kind of) dead lock.

My Laptop specification:
Processor: AMD A8-3500M APU with Radeon(tm) HD Graphics × 4 
Memory: 5.3 GiB
OS: Ubuntu 12.04 (64 bit)

Ruby version: Ruby 1.9.3p194
Rails version: Rails 3.2.8
RVM version: RVM 1.16.8 (stable)
Roo version: Roo (1.11.1)

Is there anyone ever met the same problem like this?

Thank you and sorry for bad grammar.

**Comment by stevendaniels** [comment]
Is this issue still valid? Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
No response after 4 weeks. I recommend closing this issue.

**Comment by ksugiarto** [comment]
Hei, @stevendaniels and yes thanks for remind me on this issue.

I believe on current version will be no problem. I'll close this issue then :D
