### ISSUE TITLE
Opening password-protected excel files?

### ISSUE THREAD

**Issue by bensomers** [roo-rb/roo#399]
This feels like an awfully long shot, but I figured it couldn't hurt to ask.

Have you investigated whether it would be possible (and if so, what would be involved) to use roo to open password-protected .xlsx files? Not cracking passwords - I know the password - but just being able to open it in code. I'm willing to work up a PR if there's a viable approach - my alternative is probably to add a daily permanent human-intervention step to an otherwise totally automated system.

From what I can tell, the only officially-supported options from Microsoft involve their C# Interop library - but I have been able to find some open-source implementations (all quite old, and possibly only working at certain points in time) in Perl and C that could maybe be ported.

(My hunch is that the amount of maintenance headache suggested would mean this would not really be suitable for mainline inclusion? But even if it involves a monkeypatch for my own system, any suggestions would be welcome)

**Comment by goosetherumfoodle** [comment]
@bensomers having this issue now. Did you ever end up finding a solution, or alternative gem?

**Comment by bensomers** [comment]
I have not. The best lead I ever got were the implementations mentioned above - I don't have the links handy, but could probably find them again with 30-60m of research. I strongly suspect for my use case this will just wind up being done by hand permanently, because I don't think I'm going to be able to get the time to write this.

**Comment by cescue** [comment]
I ran into this issue myself and managed a (very clumsy) workaround that entails using an excel macro to remove passwords. Here's a brief overview of the approach I took:

1. Specify a directory to temporarily store password-protected xlsx files. Think of this as a "staging" area for password-protected files.

2. Create an excel macro that will open all files in the directory created above, and re-save them without passwords. It is assumed that all files in the directory will have the same password. Both the directory and the password are hard-coded in the macro.

3. In your ruby script, relocate files to the staging area and call the excel macro.

Here's an example of how the process might look look in a ruby script:

```ruby
require 'fileutils'
require 'roo'

excel_binary = '/path/to/excel.exe'
password_removal_macro = '/path/to/your/macro.xlsm'
xlsx = '/path/to/your/spreadsheet.xlsx'

# Move the target spreadsheet to the staging directory, remove its password
# by calling the excel macro, and then move it back to its original location
def remove_password(excel_binary, password_removal_macro, xlsx)
  FileUtils.mv(xlsx, "/path/to/your/staging/directory/#{File.basename(xlsx)}")

  `"#{excel_binary}" "#{password_removal_macro}"`

  FileUtils.mv("/path/to/your/staging/directory/#{File.basename(xlsx)}", xlsx)
end

remove_password(excel_binary, password_removal_macro, xlsx)

spreadsheet = Roo::Spreadsheet.open(xlsx)

# ...

```

And here's the excel macro I'm using. I almost never use VBA, so it's probably trash - that said, it seems to work:

```vba
Sub Workbook_Open()
  Application.DisplayAlerts = False

  'All files in this path will be "unlocked"; that is, they will be opened with
  'a static password, and re-saved with no password.
  pathToUnlock = Application.ActiveWorkbook.Path + "\path\to\locked\files"
  fileToUnlock = Dir(pathToUnlock + "\*.xlsx")
  
  Do While Len(fileToUnlock) > 0
    Debug.Print ("Opening " + fileToUnlock + ".")
    Workbooks.Open Filename:=pathToUnlock + "\" + fileToUnlock, Password:="<Your Password Here>"
    Workbooks(fileToUnlock).SaveAs Filename:=pathToUnlock + "\" + fileToUnlock, Password:=""
    Workbooks(fileToUnlock).Close SaveChanges:=False
    fileToUnlock = Dir
  Loop
  
  ThisWorkbook.Saved = True
  Application.Quit
End Sub
```

**Comment by tgturner** [comment]
Closing this issue because after some research, it doesn't look like this is possible. Thanks for the suggested workaround @cescue
