### ISSUE TITLE
Incorrect float and date parsing from ver. 2007 .xlsx in .to_csv

### ISSUE THREAD

**Issue by kinnairdclan** [roo-rb/roo#402]
I apologize for not providing a gist or sample file for this issue. Our spreadsheets contain personally identifiable information, and we have a bit of a catch-22 on our hands as we cannot alter our source files for testing without inadvertently fixing them (Opening and saving with Excel 2016 performs silent alterations on the file that fix it). I will provide screenshots and XML of the file in question.

A client submits a file to our system that repeatedly gets parsed incorrectly. This file is .xlsx version 12.x (2007). An example row is below. This is the data that we want to see when Roo parses the file:

![goodstuff](https://user-images.githubusercontent.com/8727429/29632362-0912811a-8800-11e7-913d-bce235563e95.PNG)

However, running Roo::Excelx.new against the virgin file opens it and parses floats and dates incorrectly:

![badstuff](https://user-images.githubusercontent.com/8727429/29632512-737dd702-8800-11e7-81e4-ec04843015e2.PNG)

Problems: 
217979.00 is now a date, 96.5 is now a date, and date 5/31/2017 is now 42886. This is a pattern across the entire file: floats become dates, and dates become integers.

XLSX segment of the virgin file (hasn't been opened with a modern Excel, it's version 12.x etc.):

`<t xml:space="preserve">1STALL</t></is></c><c s="3" t="inlineStr" r="B2"><is><t xml:space="preserve">3013099116</t></is></c><c s="4" r="C2"><v>212615.94</v></c><c s="5" r="D2"><v>217979.00</v></c><c s="6" r="E2"><v>6.125000</v></c><c s="5" r="F2"><v>360</v></c><c s="7" r="G2"><v>42886</v></c><c s="3" t="inlineStr" r="H2"><is><t xml:space="preserve">OC</t></is></c><c s="3" t="inlineStr" r="I2"><is><t xml:space="preserve">P</t></is></c><c s="4" r="J2"><v>96.500000</v></c><c s="4" r="K2"><v>96.500000</v></c><c s="3" t="inlineStr" r="L2"><is><t xml:space="preserve">FHAFIX  </t></is></c><c s="8" r="M2"><v>1</v></c>`

XLSX of the file once it has been opened and saved by a modern version of Excel:

`<row r="2" spans="1:41"><c r="A2" s="3" t="s"><v>41</v></c><c r="B2" s="3" t="s"><v>42</v></c><c r="C2" s="4"><v>212615.94</v></c><c r="D2" s="5"><v>217979</v></c><c r="E2" s="6"><v>6.125</v></c><c r="F2" s="5"><v>360</v></c><c r="G2" s="7"><v>42886</v></c><c r="H2" s="3" t="s"><v>43</v></c><c r="I2" s="3" t="s"><v>44</v></c><c r="J2" s="4"><v>96.5</v></c><c r="K2" s="4"><v>96.5</v></c><c r="L2" s="3" t="s"><v>45</v></c><c r="M2" s="8"><v>1</v></c>`

I'm assuming that Roo is just working off the information that the bad file give it and saying that, for example, 42886 is simply 42886. However, the updated file contains the same value field and parses correctly--any pointers as to where to look to start fixing this file?

Any assistance/suggestions greatly appreciated!

**Comment by VitaliyAdamkov** [comment]
I've encountered the same issue with parsing floats as datetimes.
After some digging into I've found the point where format detection goes wrong:
#### cat lib/roo/excelx/format.rb
```
      def to_type(format)
        format = format.to_s.downcase
        if (type = EXCEPTIONAL_FORMATS[format])
          type
        elsif format.include?('#')
          :float
        elsif !format.match(/d+(?![\]])/).nil? || format.include?('y')
          if format.include?('h') || format.include?('s')
            :datetime
          else
            :date
          end
        elsif format.include?('h') || format.include?('s')
          :time
        elsif format.include?('%')
          :percentage
        else
          :float
        end
      end
```
When a format like '0.0 "USD"' passes in, it gets detected as :datetime, not :float.

Quick fix, that I've used, looks like this:
- `gem 'money'` in Gemfile
- cat config/initializers/roo_excelx_currency_formats.rb
```
module Roo
  class Excelx
    module Format
      STANDARD_CURRENCIES = Money::Currency.table.keys.map(&:to_s)

      def to_type(format)
        format = format.to_s.downcase
        if (type = EXCEPTIONAL_FORMATS[format])
          type
        elsif format.include?('#') || currency_format?(format)
          :float
        elsif !format.match(/d+(?![\]])/).nil? || format.include?('y')
          if format.include?('h') || format.include?('s')
            :datetime
          else
            :date
          end
        elsif format.include?('h') || format.include?('s')
          :time
        elsif format.include?('%')
          :percentage
        else
          :float
        end
      end
      module_function :to_type

      private

      def currency_format?(format)
        STANDARD_CURRENCIES.any? { |i| format.include? i }
      end
      module_function :currency_format?
    end
  end
end
```

**Comment by tgturner** [comment]
@kinnairdclan It seems like something must be corrupted with the original file, if saving the file then corrects the issues. Are you able to recreate files that cause this issue, is this a one time issue with a single file?

**Comment by kinnairdclan** [comment]
Hi @tgturner, I appreciate the response. Since reporting this issue we identified our client's _export_ libraries as the problem child, creating old, bad spreadsheets. They were proprietary I believe, and once our client upgraded their export libraries we began to parse them correctly with Roo (the spreadsheets were Excel 2016-compatible on their way into the parser). That being said, from @VitaliyAdamkov 's message above it appears that bad float-as-datetime parsing may still be an issue in the library with some Excel 2007-era spreadsheets. Unfortunately, we are long past the issue here and I have no sample files to provide.

**Comment by tgturner** [comment]
@VitaliyAdamkov I am no longer able to recreate your issue on current Master. Can you provide a spreadsheet that demonstrates your issue.

**Comment by VitaliyAdamkov** [comment]
@tgturner It is strange, but now me neither, nor at 2.7.1 (from rubygems), nor master branch version. I used the same files everywhere, but issue is gone.

**Comment by tgturner** [comment]
Woo! Thanks for confirming. Closing this issue!
