### ISSUE TITLE
Suggestion: have HeaderRowNotFoundError report which header is missing

### ISSUE THREAD

**Issue by aepyornis** [roo-rb/roo#412]
Right now if you call #parse with a hash on a spreadsheet with header that isn't found in the sheet it raises `Roo::HeaderRowNotFoundError`

for example if you have a simple spreadsheet like such
``` 
header1, header2
one,two
```

and you call  
``` rb
Roo::Spreadsheet.open(FILE_PATH).parse(header1: 'header1', header3: 'header3') 
````

It will raise `Roo::HeaderRowNotFoundError` but there doesn't appear to be a way to easily know which header (in this case "header3") is missing from the spreadsheet. I find the HeaderRowNotFoundError helpful when debugging big spreadsheets with many columns, but it would be even more useful to know which header was missing from the sheet!

**Comment by tgturner** [comment]
@aepyornis This sounds like a great idea, can you open a PR?
