### ISSUE TITLE
not an issue, just question please

### ISSUE THREAD

**Issue by mlotfi2005** [roo-rb/roo#425]
Can you please provide the file new_prices.xlsx ?
Thanks,

**Comment by mlotfi2005** [comment]
because I did not understand 
sheet.parse(id: /UPC|SKU/, qty: /ATS*\sATP\s*QTY\z/)
# => [{:id => 727880013358, :qty => 12}, ...]

what are UPC , SKU ATS ,  ?

**Comment by willlahr** [comment]
Those are terms from retail - you can look them up on wikipedia. UPC is the barcode, SKU is the 'stock keeping unit'

**Comment by tgturner** [comment]
Thanks @willlahr!
