### ISSUE TITLE
each() should skip the header row?

### ISSUE THREAD

**Issue by paneq** [roo-rb/roo#428]
`Roo::Base#each()` method does not skip the row detected as header.

https://gist.github.com/paneq/4e866bf8be2e2c3c35bc396944f5b630

No matter what I try I get:

```
{:name=>"name", :isbn=>"isbn", :quantity=>"quantity"}
{:name=>"Old Book", :isbn=>9781609731939, :quantity=>10}
{:name=>"Recent Book", :isbn=>9781609737207, :quantity=>1}
{:name=>"New Book", :isbn=>9781609731946, :quantity=>2}
{:name=>"Ignore Because Quantity Blank", :isbn=>"978XYZ", :quantity=>nil}
```

and I would prefer:

```
{:name=>"Old Book", :isbn=>9781609731939, :quantity=>10}
{:name=>"Recent Book", :isbn=>9781609737207, :quantity=>1}
{:name=>"New Book", :isbn=>9781609731946, :quantity=>2}
{:name=>"Ignore Because Quantity Blank", :isbn=>"978XYZ", :quantity=>nil}
```

I tried:

* `each(headers: :first_row)`
* `each(name: 'name',isbn: 'isbn',quantity: 'quantity')`
* `each(header_search: %w(name isbn quantity))`

It appears to me that:

```
  def each(options = {})
    return to_enum(:each, options) unless block_given?

    if options.empty?
      1.upto(last_row) do |line|
        yield row(line)
      end
    else
      clean_sheet_if_need(options)
      search_or_set_header(options)
      headers = @headers ||
                Hash[(first_column..last_column).map do |col|
                  [cell(@header_line, col), col]
                end]

      @header_line.upto(last_row) do |line|
        yield(Hash[headers.map { |k, v| [k, cell(line, v)] }])
      end
    end
  end
```

I expected it to be `(@header_line+1).upto(last_row)`.

**Comment by ej2015** [comment]
Seems the header option is available in [`parse` method](https://github.com/roo-rb/roo/blob/3ed05e1caef0ce3c5db5c19f1fa14e6f74193079/lib/roo/base.rb#L309). I feel the intention is to use `parse` instead of `each` directly.

**Comment by tgturner** [comment]
@paneq  currently `each` does not support skipping the header row, feel free to submit a PR with a suggestion!
