### ISSUE TITLE
determining if file is a stream or not

### ISSUE THREAD

**Issue by bigos** [roo-rb/roo#439]
In your code

https://github.com/roo-rb/roo/blob/3ed05e1caef0ce3c5db5c19f1fa14e6f74193079/lib/roo/base.rb#L374

you check if the file object responds to seek.

That causes problems. I have an object of Tempfile class that responds to seek. The documentation of Tempfile does not seem to list seek as one of its methods and I need it to treat it as a regular file. What should I do?

**Comment by bigos** [comment]
https://stackoverflow.com/questions/51668905/how-do-i-determine-if-temfile-is-a-stream-or-not

**Comment by bigos** [comment]
Looks like the solution has been found. See the SO question.

**Comment by tgturner** [comment]
Roo::OpenOffice is expecting a filename, not an open file.
