### ISSUE TITLE
[FetureRequest] Allow default nil value if no header matched

### ISSUE THREAD

**Issue by hutusi** [roo-rb/roo#446]
If there is no header matched when parsing a sheet, roo will raise Roo::HeaderRowNotFoundError.

Can roo allow set nil value instead of raise Roo::HeaderRowNotFoundError by options?

**Comment by tgturner** [comment]
@hutusi Thank you for your suggestion. There are a couple of ideas around this that are being thought about. I'm going to mark this issue as a duplicate in favor of https://github.com/roo-rb/roo/pull/427

If you have any more thoughts feel free to add them to that discussion!
