### ISSUE TITLE
Is it possible to make the temporary directories (/tmp) allow an optional path?

### ISSUE THREAD

**Issue by info-rchitect** [roo-rb/roo#460]
Depending on the computer location, /tmp is either very large or very small.  Could there be a way to configure the location of the temporary directories roo creates?

thx

**Comment by chopraanmol1** [comment]
Yes, you can configure temporary directories using the following approach:
1. You can set environment variable **ROO_TMP** (`ENV["ROO_TMP"]`) to change the default temp directory of roo.
2. You can use `tmpdir_root` option while intializing some spreadsheet instance. 
  e.g. `Roo::Excelx.new("your_file_name.xlsx", tmpdir_root: "location_to_new_temp_dir")`

**Comment by info-rchitect** [comment]
@chopraanmol1 thanks very much for the quick response!
