### ISSUE TITLE
How can I make Roo clean up the temporary directories?

### ISSUE THREAD

**Issue by myfitment** [roo-rb/roo#474]
Is it necessary to have  cron job remove these directories periodically? I find I am having to do it by hand after receiving warnings about running out of space. Is there any way to set roo to remove the directories after completion?

**Comment by chopraanmol1** [comment]
Try calling `Roo::Excelx#close` method once you have finished processing.
```
sheet = Roo::Excelx.new('..../path/filename.xlsx')
# process the excel file
#..... 
#..... 
# processing done
sheet.close
```

Related PR  #211 #329 
#329 onwards it is not explicitly required to call close, tmpdir cleanup is handled by finalizer called during GC.  Can you provide gist which reproduce your issue on latest version without calling `close`.
