### ISSUE TITLE
Regression: ArgumentError in extract_coordinate in 2.8.1

### ISSUE THREAD

**Issue by andykelk** [roo-rb/roo#489]
### Steps to reproduce

Attached test case and sample file

[test.xlsx](https://github.com/roo-rb/roo/files/2784538/test.xlsx)
[test-case.rb.txt](https://github.com/roo-rb/roo/files/2784539/test-case.rb.txt)

### Issue
When opening an XLSX spreadsheet with hyperlinks, receive an `ArgumentError` in `lib/roo/utils.rb:20`

I've tried cutting back the file to find the offending row but it starts working after a while and seems to be somewhat inconsistent in reproduction with the same visible data in Excel.

File was written by Excel for Mac v16.21

### System configuration
**Roo version**: 2.8.1. The issue appeared when updating to 2.8.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by andykelk** [comment]
Having looked at this further, the issue appears to be with the definition of a hyperlink. Excel writes the hyperlink once and then references the same link across a range:

```
<hyperlink ref="A2:A5" r:id="rId1"
```

This raises an exception in `Roo::Utils::extract_coordinate` as it contains a `:` rather than just alphanumeric characters.

The previous implementation in 2.7.1 (`Roo::Utils::split_coordinate`) used a regex to just grab the first coordinate and would ignore the second coordinate in the range.

I'm probably not intimate enough with the internals of XLSX documents to propose a fix but the previous implementation certainly seemed to work for our purposes although it seems it would have missed the hyperlink being associated with all but the first cell in the range.

I tested the attached patch which solved the issue for me but seems like a fairly ugly hack.
[fix_hyperlink_range.patch.txt](https://github.com/roo-rb/roo/files/2785074/fix_hyperlink_range.patch.txt)

**Comment by chopraanmol1** [comment]
@andykelk Thank you for reporting this issue in a detailed manner.
