### ISSUE TITLE
Explicit "text" columns being imported at :float anyway

### ISSUE THREAD

**Issue by mbhnyc** [roo-rb/roo#53]
Hey guys-

So, I have a spreadsheet a column of unformatted phone numbers (we have international users, so a one-size-fits-all format is impractical) — most of these are simply numbers, but even when the xlsx (or xls) column type is set to "Text", these still come in as Floats and end up imported with a ".0" at the end.

This is obviously incorrect, but I really thought the column type would be respected.

Am I doing anything obviously wrong here, or is there an issue?

**Comment by stevendaniels** [comment]
Does this issue still exist in the current version of Roo?

I now it's been a while, but can you create a gist that illustrates this issue?

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone this repo locally, add a stripped down version of the offending spreadsheet to the repo, and push the changes to the gist.
3. Paste the gist url here.

[Here's a sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c)

**Comment by OmniBus** [comment]
From @carlost 's comment, it is pretty safe to make an assumption interpreting format '@' is string (text) type. It solves many long standing issues .

```ruby
return :string if format == '@' 
```

Modify file
roo/lib/roo/excelx.rb

```ruby
      def to_type(format)
        format = format.to_s.downcase
        if (type = EXCEPTIONAL_FORMATS[format])
          type
        elsif format.include?('#')
          :float
        elsif !format.match(/d+(?![\]])/).nil? || format.include?('y')
          if format.include?('h') || format.include?('s')
            :datetime
          else
            :date
          end
        elsif format.include?('h') || format.include?('s')
          :time
        elsif format.include?('%')
          :percentage
        elsif format == '@'
          :string
        else
          :float
        end
      end
```

**Comment by OmniBus** [comment]
@stevendaniels 
Make float default surprise everyone. It'd better to leave programmer to decide how to interpret the string if there is no cue to interpret it.

**Comment by stevendaniels** [comment]
I've submitted a request (#240) that proper type support to Excel. It's a big request, so it will probably take some time before it gets pulled into master.

**Comment by stevendaniels** [comment]
#240 resolves this issue.   Add the following to your gemfile to install it.

    gem 'roo', git: 'git://github.com/roo-rb/roo.git' 

I will work on publishing a new version of the gem to Rubygems this weekend.

**Comment by dkumar431** [comment]
@stevendaniels 
Is this issue already fixed? I have some numeric values (50961713356) on my excel, but it's reading them as 50961713356.0. Basically i always wants the values to be read as String.

**Comment by letiesperon** [comment]
Any updates on this? It's adding a '.0' on all my columns like id or zip code 😬

**Comment by Manthan2211** [comment]
Trying to convert that column to column.to_i.
I hope this patch is working for you.

**Comment by pathakh** [comment]
you can't convert column.to_i as it will get rid of the leading 0s.
