### ISSUE TITLE
New Release with fix for Roo::Base#each_with_pagename

### ISSUE THREAD

**Issue by ttstarck** [roo-rb/roo#606]
Is it possible to get a new patch release out to fix the degradation from version 2.10.0?

Much appreciated!

**Comment by kakubin** [comment]
@simonoff or @Empact 
Would you mind publishing new version 2.10.1 ?

**Comment by Empact** [comment]
@kakubin Thanks for the bump, I released in https://github.com/roo-rb/roo/commit/dad35374f54779b3dc5c701d21f295a78aa91c0d lmk if anything is amiss.
