### ISSUE TITLE
Undefined method <= on Excelx.open

### ISSUE THREAD

**Issue by agius** [roo-rb/roo#70]
Trying to open a non-zipped .xlsx file on the local machine. Here's the call:

    @spreadsheet = Roo::Excelx.new(file.path, :file_warning => :ignore)

And getting this error:

    undefined method `<=' for nil:NilClass
    rubyzip (1.0.0) lib/zip/central_directory.rb:80:in `read_e_o_c_d'
    rubyzip (1.0.0) lib/zip/central_directory.rb:105:in `read_from_stream'
    rubyzip (1.0.0) lib/zip/file.rb:76:in `block in initialize'
    rubyzip (1.0.0) lib/zip/file.rb:75:in `open'
    rubyzip (1.0.0) lib/zip/file.rb:75:in `initialize'
    rubyzip (1.0.0) lib/zip/file.rb:95:in `new'
    rubyzip (1.0.0) lib/zip/file.rb:95:in `open'
    roo (1.12.2) lib/roo/excelx.rb:569:in `extract_content'
    roo (1.12.2) lib/roo/excelx.rb:89:in `block in initialize'
    roo (1.12.2) lib/roo/base.rb:565:in `block in make_tmpdir'

Looks like the file is missing some comment / header section that maybe is important? Sorry, I don't know Office formats very well :( Tried adding a nil catch to that line in rubyzip, but that creates more issues down the line.

Any suggestions / ideas would be awesome. Thanks!

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
Roo's ```master``` branch uses ```rubyzip```, so this issue doesn't exist any more. Closing it.
