### ISSUE TITLE
Roo::Spreadsheet.open extension with a dot.

### ISSUE THREAD

**Issue by Exoth** [roo-rb/roo#73]
It would be great if `Roo::Spreadsheet.open` accepts extensions not only in 'xls' format, but also in '.xls' format, as it would make it possible to use the results of `File.extname`  method without removing its dot.

**Comment by stevendaniels** [comment]
Is this feature request still applicable? 
[Roo::Spreadsheet](https://github.com/roo-rb/roo/blob/master/lib%2Froo%2Fspreadsheet.rb#L16-L27) seems to allow for extensions with our without dots.

I recommend closing this issue.

**Comment by stevendaniels** [comment]
@Exoth  Can you close this issue? It is no longer valid. Thanks.

**Comment by Exoth** [comment]
Yep, it should work now. Thanks.
