### ISSUE TITLE
Opening an IO stream or a file ?

### ISSUE THREAD

**Issue by housekeeper** [roo-rb/roo#75]
Hi,

In CSV we have the facility to open an IO stream or a file 

````ruby
# raw data could also be an uploaded file 
# which remains in memory
raw_data = File.open(file).read 
csv_data = CSV.new(raw_data)
````
or 

````ruby
CSV.open(file)
# etc etc
````
Is it possible to just give roo an IO stream if I can specify its type and parse? 
I want to open excel based files without hitting the file system is this possible 

Many thanks in advance. 

Kind regards,
Carl

**Comment by stevendaniels** [comment]
Is anyone still interested in this feature?

**Comment by ricktessner** [comment]
I would definitely be interested in something like this. Would be very handy to create a placeholder object that has the same interface as a Roo::CSV instance.

For instance, right now, I'm wanting a default instance of Roo::CSV.new(StringIO.new('')). The current code is using a default value of nil which naturally trickles up to elsewhere in the code throwing an "undefined method ... for nil:NilClass".

Being able to create, in effect, a null object that responds to the Roo::CSV interface would be helpful.

**Comment by sdistefano** [comment]
This fix doesn't work for ROO::CSV yet
