### ISSUE TITLE
Zip end of central directory signature not found (Zip::ZipError)

### ISSUE THREAD

**Issue by jgwconsulting** [roo-rb/roo#80]
This error is thrown when attempting to read a particular xlsx file:

Zip end of central directory signature not found (Zip::ZipError)

A gist fix has been posted here (I haven't tried it yet):

https://gist.github.com/roblingle/1333908

Note the fix was written for xlsm files but a comment confirms that it also works for xlsx files.

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Does any one know if this issue still exists in the current version of Roo?

**Comment by stevendaniels** [comment]
@simonoff No response after two weeks. I recommend closing this issue.

**Comment by jeromewilson** [comment]
Sorry for the late reply. I'm not doing Rails work any more (back to boring old C#) so it's tricky for me to test, I'm afraid. If it is still a problem it's probably best tracked by RubyZip anyway as it was doubtless an issue with that codebase, rather than Roo.

**Comment by simonoff** [comment]
Due the gist it's a bug in zip gem not in roo or rubyzip.
