### ISSUE TITLE
ruby 2.0.0

### ISSUE THREAD

**Issue by shenhf** [roo-rb/roo#82]
CPU 100% under ruby 2.0.0,  1.9.2 works ok!

**Comment by stevendaniels** [comment]
If I'm not mistaken, this issue seems to affect an older version of Roo.
[Roo::Base](https://github.com/roo-rb/roo/blob/master/lib/roo/base.rb#L163-L166) has the inspect method  @whistlerbrk suggested.

This issue should probably be closed.

**Comment by pmneve** [comment]
@stevendaniels If you mean 1.13.2 that is currently the only version available through rubygems...  A lot of folks who use roo would like to get the latest and have difficulty (corporate security idiocies) getting at it from github.

**Comment by stevendaniels** [comment]
I too wish Roo would be updated on Rubygems. I created an issue (#172) that for that, but I haven't heard anything yet.

**Comment by simonoff** [comment]
@pmneve you can try beta release on rubygems.

**Comment by pmneve** [comment]
@simonoff super, will do asap!

**Comment by stevendaniels** [comment]
This issue was resolved and ver 2.0.0 of Roo is available on rubygems. Closing.
