### ISSUE TITLE
is not an Excel-xlsx file

### ISSUE THREAD

**Issue by swiftslipper** [roo-rb/roo#83]
I get the above error when I'm trying to open a temporary uploaded file. Trace gives out 

`/gems/roo-1.12.2/lib/roo/base.rb:524:in `file_type_check'`

Looking at that line, it checks for FILE EXTENSION to confirm FILE TYPE.

Isn't there a better way to check? All temporary filenames have no extensions. I have to manually rename it, and that's just bad.

UPDATE: read the usage info here, which is more up to date than what the main site has. Apparently, I can use open and just pass the file. That's good. But this file type checking should still be improved, imo. I think if this issue stays here open / closed, will help the ones like myself.

**Comment by stevendaniels** [comment]
I think this could be added to the Readme.

**Comment by stevendaniels** [comment]
@swiftslipper Can we close this issue?
