### ISSUE TITLE
Force text type for all fields?

### ISSUE THREAD

**Issue by irashkin** [roo-rb/roo#86]
Hi, this is great, I've gotten a prototype app up and running in a few hours, and it is working great. Just one thing - I've got fields that look like numbers, but aren't: for example, employee_id; depending on the company, employee_id may be numeric or alpha-numeric, but I won't know in advance, so want to store them all as strings. However, in sample data that has all numeric ids, roo wants to interpret them as floats, and so I end with with an id.0 in my database, leading to all sorts of trouble. This is related to similar issue https://github.com/Empact/roo/issues/53, except that in my case, I can't even guarantee that the field will be explicitly marked text - it is up to the client to manage the spreadsheets, and that means total unreliability. 
Is there any way, that anyone can think of, to force ALL fields to be interpreted as text? For my purposes, that would be fine - there's nothing in my data that is not text, so a global option on open would be ideal.
Any ideas?
Thanks, 
Ian

**Comment by pmneve** [comment]
@emerson-h Would like to know ETA of this feature as well!

**Comment by pmneve** [comment]
@emerson-h Would also like ETA on this feature!

**Comment by lluis** [comment]
there's a workaround on #139:

    cell = s.excelx_value(row,col) if s.excelx_type(row,col) == [:numeric_or_formula, "GENERAL"]

**Comment by stevendaniels** [comment]
This is an interesting request. It should be possible, but it would require some work. I can definitely see the use case for this request, but it would require a bit of work. 

@simonoff Do you think this feature should be added to Roo?

**Comment by stevendaniels** [comment]
#240 adds a methods for `xlsx` spreadsheets called `formatted_value` that creates a text value for all cell types.
