### ISSUE TITLE
Add support for extraction of change tracking info from Excel files

### ISSUE THREAD

**Issue by allanlewis** [roo-rb/roo#89]
Would it be possible to add support for reading change tracking information from Excel files?

What I mean is, if change tracking was turned on in Excel, it should be possible to read the change history of the file, including metadata like which changed have been reviews and which haven't.

I'm using Excel 2010 & 2013, so I'm mostly thinking of XLSX files here. According to the XML schema (available from [ECMA](http://www.ecma-international.org/publications/standards/Ecma-376.htm "Standard ECMA-376")), there is an element named `revisions` of type `CT_Revisions` that appears to hold the relevant data.

Specifically, it would be great if we could have a `revisions` method that works in a similar way to the existing `comment` and `comments` methods, i.e. `s.revisions` returns all the revisions, and `s.revision(row, col)` returns any revisions for the specified cell.

**Comment by stevendaniels** [comment]
This is an interesting feature request. Anyone interested in implementing it?

**Comment by stevendaniels** [comment]
Based on the lack of interest,I recommend closing this issue.

**Comment by stevendaniels** [comment]
I'm currently considering this issue and #185 as part of a future upgrade to Roo.

**Comment by stevendaniels** [comment]
Closing due to lack of interest.
