### ISSUE TITLE
No close method

### ISSUE THREAD

**Issue by irashkin** [roo-rb/roo#91]
Apologies, I'm still quite new to RoR, and maybe I'm missing something obvious to everyone else, but how do I close a Roo file once open? I've got spreadsheet = Roo::Spreadsheet.open(file_name) just fine, but I want to do either spreadsheet.close, or preferably, Roo::Spreadsheet.open(self.file_name) do |spreadsheet| ... end. 
Is there a way to do this, or is it something missing? I ask because I'm running into problems deleting files after parsing them, and I'm pretty sure it's because they still are locked open by Roo.

**Comment by stevendaniels** [comment]
This issue seems to be related to https://github.com/roo-rb/roo/issues/143

**Comment by stevendaniels** [comment]
This issue has been resolved. Closing.
